#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Domain.Roles.Contenders.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinkMe")]
	public partial class ContendersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCandidateListEntryEntity(CandidateListEntryEntity instance);
    partial void UpdateCandidateListEntryEntity(CandidateListEntryEntity instance);
    partial void DeleteCandidateListEntryEntity(CandidateListEntryEntity instance);
    partial void InsertCandidateListEntity(CandidateListEntity instance);
    partial void UpdateCandidateListEntity(CandidateListEntity instance);
    partial void DeleteCandidateListEntity(CandidateListEntity instance);
    partial void InsertJobApplicationEntity(JobApplicationEntity instance);
    partial void UpdateJobApplicationEntity(JobApplicationEntity instance);
    partial void DeleteJobApplicationEntity(JobApplicationEntity instance);
    partial void InsertCandidateNoteEntity(CandidateNoteEntity instance);
    partial void UpdateCandidateNoteEntity(CandidateNoteEntity instance);
    partial void DeleteCandidateNoteEntity(CandidateNoteEntity instance);
    partial void InsertExternalApplicationEntity(ExternalApplicationEntity instance);
    partial void UpdateExternalApplicationEntity(ExternalApplicationEntity instance);
    partial void DeleteExternalApplicationEntity(ExternalApplicationEntity instance);
    #endregion
		
		public ContendersDataContext() : 
				base(global::LinkMe.Domain.Roles.Properties.Settings.Default.LinkMeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContendersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContendersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContendersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContendersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		internal System.Data.Linq.Table<CandidateListEntryEntity> CandidateListEntryEntities
		{
			get
			{
				return this.GetTable<CandidateListEntryEntity>();
			}
		}
		
		internal System.Data.Linq.Table<CandidateListEntity> CandidateListEntities
		{
			get
			{
				return this.GetTable<CandidateListEntity>();
			}
		}
		
		internal System.Data.Linq.Table<JobApplicationEntity> JobApplicationEntities
		{
			get
			{
				return this.GetTable<JobApplicationEntity>();
			}
		}
		
		internal System.Data.Linq.Table<CandidateNoteEntity> CandidateNoteEntities
		{
			get
			{
				return this.GetTable<CandidateNoteEntity>();
			}
		}
		
		internal System.Data.Linq.Table<ExternalApplicationEntity> ExternalApplicationEntities
		{
			get
			{
				return this.GetTable<ExternalApplicationEntity>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SplitGuids", IsComposable=true)]
		public IQueryable<SplitGuidsResult> SplitGuids([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string delimiter, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string input)
		{
			return this.CreateMethodCallQuery<SplitGuidsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), delimiter, input);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOrganisationFullName", IsComposable=true)]
		public string GetOrganisationFullName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(1)")] System.Nullable<char> separator)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, separator).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsOrganisationDescendent", IsComposable=true)]
		public System.Nullable<bool> IsOrganisationDescendent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> parentId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> childId)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentId, childId).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SplitInts", IsComposable=true)]
		public IQueryable<SplitIntsResult> SplitInts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string delimiter, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string input)
		{
			return this.CreateMethodCallQuery<SplitIntsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), delimiter, input);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CandidateListEntry")]
	internal partial class CandidateListEntryEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _candidateListId;
		
		private System.DateTime _createdTime;
		
		private System.Nullable<System.Guid> _jobApplicationId;
		
		private System.Guid _candidateId;
		
		private System.Nullable<System.Guid> _createdById;
		
		private System.Nullable<System.Guid> _ownedById;
		
		private System.Nullable<byte> _jobApplicationStatus;
		
		private EntityRef<CandidateListEntity> _CandidateListEntity;
		
		private EntityRef<JobApplicationEntity> _JobApplicationEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncandidateListIdChanging(System.Guid value);
    partial void OncandidateListIdChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    partial void OnjobApplicationIdChanging(System.Nullable<System.Guid> value);
    partial void OnjobApplicationIdChanged();
    partial void OncandidateIdChanging(System.Guid value);
    partial void OncandidateIdChanged();
    partial void OncreatedByIdChanging(System.Nullable<System.Guid> value);
    partial void OncreatedByIdChanged();
    partial void OnownedByIdChanging(System.Nullable<System.Guid> value);
    partial void OnownedByIdChanged();
    partial void OnjobApplicationStatusChanging(System.Nullable<byte> value);
    partial void OnjobApplicationStatusChanged();
    #endregion
		
		public CandidateListEntryEntity()
		{
			this._CandidateListEntity = default(EntityRef<CandidateListEntity>);
			this._JobApplicationEntity = default(EntityRef<JobApplicationEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_candidateListId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid candidateListId
		{
			get
			{
				return this._candidateListId;
			}
			set
			{
				if ((this._candidateListId != value))
				{
					if (this._CandidateListEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncandidateListIdChanging(value);
					this.SendPropertyChanging();
					this._candidateListId = value;
					this.SendPropertyChanged("candidateListId");
					this.OncandidateListIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobApplicationId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> jobApplicationId
		{
			get
			{
				return this._jobApplicationId;
			}
			set
			{
				if ((this._jobApplicationId != value))
				{
					if (this._JobApplicationEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjobApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._jobApplicationId = value;
					this.SendPropertyChanged("jobApplicationId");
					this.OnjobApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_candidateId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid candidateId
		{
			get
			{
				return this._candidateId;
			}
			set
			{
				if ((this._candidateId != value))
				{
					this.OncandidateIdChanging(value);
					this.SendPropertyChanging();
					this._candidateId = value;
					this.SendPropertyChanged("candidateId");
					this.OncandidateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdById", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> createdById
		{
			get
			{
				return this._createdById;
			}
			set
			{
				if ((this._createdById != value))
				{
					this.OncreatedByIdChanging(value);
					this.SendPropertyChanging();
					this._createdById = value;
					this.SendPropertyChanged("createdById");
					this.OncreatedByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownedById", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> ownedById
		{
			get
			{
				return this._ownedById;
			}
			set
			{
				if ((this._ownedById != value))
				{
					this.OnownedByIdChanging(value);
					this.SendPropertyChanging();
					this._ownedById = value;
					this.SendPropertyChanged("ownedById");
					this.OnownedByIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobApplicationStatus", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> jobApplicationStatus
		{
			get
			{
				return this._jobApplicationStatus;
			}
			set
			{
				if ((this._jobApplicationStatus != value))
				{
					this.OnjobApplicationStatusChanging(value);
					this.SendPropertyChanging();
					this._jobApplicationStatus = value;
					this.SendPropertyChanged("jobApplicationStatus");
					this.OnjobApplicationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CandidateListEntity_CandidateListEntryEntity", Storage="_CandidateListEntity", ThisKey="candidateListId", OtherKey="id", IsForeignKey=true)]
		public CandidateListEntity CandidateListEntity
		{
			get
			{
				return this._CandidateListEntity.Entity;
			}
			set
			{
				CandidateListEntity previousValue = this._CandidateListEntity.Entity;
				if (((previousValue != value) 
							|| (this._CandidateListEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CandidateListEntity.Entity = null;
						previousValue.CandidateListEntryEntities.Remove(this);
					}
					this._CandidateListEntity.Entity = value;
					if ((value != null))
					{
						value.CandidateListEntryEntities.Add(this);
						this._candidateListId = value.id;
					}
					else
					{
						this._candidateListId = default(System.Guid);
					}
					this.SendPropertyChanged("CandidateListEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JobApplicationEntity_CandidateListEntryEntity", Storage="_JobApplicationEntity", ThisKey="jobApplicationId", OtherKey="id", IsForeignKey=true)]
		public JobApplicationEntity JobApplicationEntity
		{
			get
			{
				return this._JobApplicationEntity.Entity;
			}
			set
			{
				JobApplicationEntity previousValue = this._JobApplicationEntity.Entity;
				if (((previousValue != value) 
							|| (this._JobApplicationEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._JobApplicationEntity.Entity = null;
						previousValue.CandidateListEntryEntities.Remove(this);
					}
					this._JobApplicationEntity.Entity = value;
					if ((value != null))
					{
						value.CandidateListEntryEntities.Add(this);
						this._jobApplicationId = value.id;
					}
					else
					{
						this._jobApplicationId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("JobApplicationEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CandidateList")]
	internal partial class CandidateListEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _name;
		
		private System.Guid _ownerId;
		
		private System.DateTime _createdTime;
		
		private bool _isDeleted;
		
		private System.Nullable<System.Guid> _sharedWithId;
		
		private int _listType;
		
		private EntitySet<CandidateListEntryEntity> _CandidateListEntryEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnownerIdChanging(System.Guid value);
    partial void OnownerIdChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    partial void OnsharedWithIdChanging(System.Nullable<System.Guid> value);
    partial void OnsharedWithIdChanged();
    partial void OnlistTypeChanging(int value);
    partial void OnlistTypeChanged();
    #endregion
		
		public CandidateListEntity()
		{
			this._CandidateListEntryEntities = new EntitySet<CandidateListEntryEntity>(new Action<CandidateListEntryEntity>(this.attach_CandidateListEntryEntities), new Action<CandidateListEntryEntity>(this.detach_CandidateListEntryEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid ownerId
		{
			get
			{
				return this._ownerId;
			}
			set
			{
				if ((this._ownerId != value))
				{
					this.OnownerIdChanging(value);
					this.SendPropertyChanging();
					this._ownerId = value;
					this.SendPropertyChanged("ownerId");
					this.OnownerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sharedWithId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> sharedWithId
		{
			get
			{
				return this._sharedWithId;
			}
			set
			{
				if ((this._sharedWithId != value))
				{
					this.OnsharedWithIdChanging(value);
					this.SendPropertyChanging();
					this._sharedWithId = value;
					this.SendPropertyChanged("sharedWithId");
					this.OnsharedWithIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listType", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int listType
		{
			get
			{
				return this._listType;
			}
			set
			{
				if ((this._listType != value))
				{
					this.OnlistTypeChanging(value);
					this.SendPropertyChanging();
					this._listType = value;
					this.SendPropertyChanged("listType");
					this.OnlistTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CandidateListEntity_CandidateListEntryEntity", Storage="_CandidateListEntryEntities", ThisKey="id", OtherKey="candidateListId")]
		public EntitySet<CandidateListEntryEntity> CandidateListEntryEntities
		{
			get
			{
				return this._CandidateListEntryEntities;
			}
			set
			{
				this._CandidateListEntryEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CandidateListEntryEntities(CandidateListEntryEntity entity)
		{
			this.SendPropertyChanging();
			entity.CandidateListEntity = this;
		}
		
		private void detach_CandidateListEntryEntities(CandidateListEntryEntity entity)
		{
			this.SendPropertyChanging();
			entity.CandidateListEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobApplication")]
	internal partial class JobApplicationEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _coverLetterText;
		
		private System.DateTime _createdTime;
		
		private System.Guid _jobAdId;
		
		private System.Nullable<System.Guid> _resumeAttachmentFileId;
		
		private System.Guid _applicantId;
		
		private System.Nullable<System.Guid> _resumeId;
		
		private bool _isDeleted;
		
		private bool _isFeatured;
		
		private byte _applicationType;
		
		private bool _isPending;
		
		private EntitySet<CandidateListEntryEntity> _CandidateListEntryEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncoverLetterTextChanging(string value);
    partial void OncoverLetterTextChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    partial void OnjobAdIdChanging(System.Guid value);
    partial void OnjobAdIdChanged();
    partial void OnresumeAttachmentFileIdChanging(System.Nullable<System.Guid> value);
    partial void OnresumeAttachmentFileIdChanged();
    partial void OnapplicantIdChanging(System.Guid value);
    partial void OnapplicantIdChanged();
    partial void OnresumeIdChanging(System.Nullable<System.Guid> value);
    partial void OnresumeIdChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    partial void OnisFeaturedChanging(bool value);
    partial void OnisFeaturedChanged();
    partial void OnapplicationTypeChanging(byte value);
    partial void OnapplicationTypeChanged();
    partial void OnisPendingChanging(bool value);
    partial void OnisPendingChanged();
    #endregion
		
		public JobApplicationEntity()
		{
			this._CandidateListEntryEntities = new EntitySet<CandidateListEntryEntity>(new Action<CandidateListEntryEntity>(this.attach_CandidateListEntryEntities), new Action<CandidateListEntryEntity>(this.detach_CandidateListEntryEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coverLetterText", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string coverLetterText
		{
			get
			{
				return this._coverLetterText;
			}
			set
			{
				if ((this._coverLetterText != value))
				{
					this.OncoverLetterTextChanging(value);
					this.SendPropertyChanging();
					this._coverLetterText = value;
					this.SendPropertyChanged("coverLetterText");
					this.OncoverLetterTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobAdId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid jobAdId
		{
			get
			{
				return this._jobAdId;
			}
			set
			{
				if ((this._jobAdId != value))
				{
					this.OnjobAdIdChanging(value);
					this.SendPropertyChanging();
					this._jobAdId = value;
					this.SendPropertyChanged("jobAdId");
					this.OnjobAdIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeAttachmentFileId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> resumeAttachmentFileId
		{
			get
			{
				return this._resumeAttachmentFileId;
			}
			set
			{
				if ((this._resumeAttachmentFileId != value))
				{
					this.OnresumeAttachmentFileIdChanging(value);
					this.SendPropertyChanging();
					this._resumeAttachmentFileId = value;
					this.SendPropertyChanged("resumeAttachmentFileId");
					this.OnresumeAttachmentFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applicantId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid applicantId
		{
			get
			{
				return this._applicantId;
			}
			set
			{
				if ((this._applicantId != value))
				{
					this.OnapplicantIdChanging(value);
					this.SendPropertyChanging();
					this._applicantId = value;
					this.SendPropertyChanged("applicantId");
					this.OnapplicantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> resumeId
		{
			get
			{
				return this._resumeId;
			}
			set
			{
				if ((this._resumeId != value))
				{
					this.OnresumeIdChanging(value);
					this.SendPropertyChanging();
					this._resumeId = value;
					this.SendPropertyChanged("resumeId");
					this.OnresumeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFeatured", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool isFeatured
		{
			get
			{
				return this._isFeatured;
			}
			set
			{
				if ((this._isFeatured != value))
				{
					this.OnisFeaturedChanging(value);
					this.SendPropertyChanging();
					this._isFeatured = value;
					this.SendPropertyChanged("isFeatured");
					this.OnisFeaturedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applicationType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte applicationType
		{
			get
			{
				return this._applicationType;
			}
			set
			{
				if ((this._applicationType != value))
				{
					this.OnapplicationTypeChanging(value);
					this.SendPropertyChanging();
					this._applicationType = value;
					this.SendPropertyChanged("applicationType");
					this.OnapplicationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPending", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool isPending
		{
			get
			{
				return this._isPending;
			}
			set
			{
				if ((this._isPending != value))
				{
					this.OnisPendingChanging(value);
					this.SendPropertyChanging();
					this._isPending = value;
					this.SendPropertyChanged("isPending");
					this.OnisPendingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="JobApplicationEntity_CandidateListEntryEntity", Storage="_CandidateListEntryEntities", ThisKey="id", OtherKey="jobApplicationId")]
		public EntitySet<CandidateListEntryEntity> CandidateListEntryEntities
		{
			get
			{
				return this._CandidateListEntryEntities;
			}
			set
			{
				this._CandidateListEntryEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CandidateListEntryEntities(CandidateListEntryEntity entity)
		{
			this.SendPropertyChanging();
			entity.JobApplicationEntity = this;
		}
		
		private void detach_CandidateListEntryEntities(CandidateListEntryEntity entity)
		{
			this.SendPropertyChanging();
			entity.JobApplicationEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CandidateNote")]
	internal partial class CandidateNoteEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.DateTime _createdTime;
		
		private System.DateTime _lastUpdatedTime;
		
		private string _text;
		
		private System.Guid _searcherId;
		
		private System.Guid _candidateId;
		
		private System.Nullable<System.Guid> _sharedWithId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    partial void OnlastUpdatedTimeChanging(System.DateTime value);
    partial void OnlastUpdatedTimeChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OnsearcherIdChanging(System.Guid value);
    partial void OnsearcherIdChanged();
    partial void OncandidateIdChanging(System.Guid value);
    partial void OncandidateIdChanged();
    partial void OnsharedWithIdChanging(System.Nullable<System.Guid> value);
    partial void OnsharedWithIdChanged();
    #endregion
		
		public CandidateNoteEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastUpdatedTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime lastUpdatedTime
		{
			get
			{
				return this._lastUpdatedTime;
			}
			set
			{
				if ((this._lastUpdatedTime != value))
				{
					this.OnlastUpdatedTimeChanging(value);
					this.SendPropertyChanging();
					this._lastUpdatedTime = value;
					this.SendPropertyChanged("lastUpdatedTime");
					this.OnlastUpdatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(500) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searcherId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid searcherId
		{
			get
			{
				return this._searcherId;
			}
			set
			{
				if ((this._searcherId != value))
				{
					this.OnsearcherIdChanging(value);
					this.SendPropertyChanging();
					this._searcherId = value;
					this.SendPropertyChanged("searcherId");
					this.OnsearcherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_candidateId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid candidateId
		{
			get
			{
				return this._candidateId;
			}
			set
			{
				if ((this._candidateId != value))
				{
					this.OncandidateIdChanging(value);
					this.SendPropertyChanging();
					this._candidateId = value;
					this.SendPropertyChanged("candidateId");
					this.OncandidateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sharedWithId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> sharedWithId
		{
			get
			{
				return this._sharedWithId;
			}
			set
			{
				if ((this._sharedWithId != value))
				{
					this.OnsharedWithIdChanging(value);
					this.SendPropertyChanging();
					this._sharedWithId = value;
					this.SendPropertyChanged("sharedWithId");
					this.OnsharedWithIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExternalApplication")]
	internal partial class ExternalApplicationEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.DateTime _createdTime;
		
		private System.Guid _positionId;
		
		private System.Guid _applicantId;
		
		private bool _isDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    partial void OnpositionIdChanging(System.Guid value);
    partial void OnpositionIdChanged();
    partial void OnapplicantIdChanging(System.Guid value);
    partial void OnapplicantIdChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    #endregion
		
		public ExternalApplicationEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid positionId
		{
			get
			{
				return this._positionId;
			}
			set
			{
				if ((this._positionId != value))
				{
					this.OnpositionIdChanging(value);
					this.SendPropertyChanging();
					this._positionId = value;
					this.SendPropertyChanged("positionId");
					this.OnpositionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applicantId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid applicantId
		{
			get
			{
				return this._applicantId;
			}
			set
			{
				if ((this._applicantId != value))
				{
					this.OnapplicantIdChanging(value);
					this.SendPropertyChanging();
					this._applicantId = value;
					this.SendPropertyChanged("applicantId");
					this.OnapplicantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SplitGuidsResult
	{
		
		private System.Nullable<System.Guid> _value;
		
		public SplitGuidsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
	}
	
	public partial class SplitIntsResult
	{
		
		private System.Nullable<int> _value;
		
		public SplitIntsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Int")]
		public System.Nullable<int> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
