<?xml version="1.0" encoding="utf-8"?>
<Database Name="LinkMe" Class="MaintenanceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LOCAL);Initial Catalog=LinkMe;Integrated Security=True" SettingsObjectName="LinkMe.TaskRunner.Test.Properties.Settings" SettingsPropertyName="LinkMeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.JobAdIndexing" Member="JobAdIndexingEntities" AccessModifier="Internal">
    <Type Name="JobAdIndexingEntity" AccessModifier="Internal">
      <Column Name="jobAdId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="modifiedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MemberIndexing" Member="MemberIndexingEntities" AccessModifier="Internal">
    <Type Name="MemberIndexingEntity" AccessModifier="Internal">
      <Column Name="memberId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="modifiedTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>