//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Web.UI.Controls.Common.ResumeEditor {
    
    
    public partial class PrimaryResumeDetails {
        
        /// <summary>
        /// spanNoContactDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanNoContactDetails;
        
        /// <summary>
        /// ucIndustryList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.IndustryList ucIndustryList;
        
        /// <summary>
        /// ucLocationCountry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.LocationCountry ucLocationCountry;
        
        /// <summary>
        /// ucLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Location ucLocation;
        
        /// <summary>
        /// spanContactDetailsDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanContactDetailsDisplay;
    }
}
