INSERT INTO linkme_owner.ProductGrantReason(id, description)
VALUES (NEWID(), 'Promotion')
INSERT INTO linkme_owner.ProductGrantReason(id, description)
VALUES (NEWID(), 'Demonstration')
INSERT INTO linkme_owner.ProductGrantReason(id, description)
VALUES (NEWID(), 'Testing')
INSERT INTO linkme_owner.ProductGrantReason(id, description)
VALUES (NEWID(), 'Trial')
INSERT INTO linkme_owner.ProductGrantReason(id, description)
VALUES (NEWID(), 'Customer goodwill due to their experience')
GO
