IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('TinyUrlMapping') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TinyUrlMapping
GO

CREATE TABLE TinyUrlMapping
(
	tinyId UNIQUEIDENTIFIER NOT NULL,
	webSite TINYINT NOT NULL,
	verticalId UNIQUEIDENTIFIER NOT NULL,
	secure BIT NOT NULL,
	longUrl NVARCHAR(1024) NOT NULL,
	contextId UNIQUEIDENTIFIER NOT NULL,
	instance INT NOT NULL
)
GO

ALTER TABLE dbo.TinyUrlMapping ADD CONSTRAINT PK_TinyUrlMapping
	PRIMARY KEY NONCLUSTERED (tinyId)
GO

