//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Web.UI.Controls.Common.Navs {
    
    
    public partial class PageHeader {
        
        /// <summary>
        /// ucOtdMemberHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.Verticals.OtdMemberHeader ucOtdMemberHeader;
        
        /// <summary>
        /// ucSharedMemberHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.Verticals.SharedMemberHeader ucSharedMemberHeader;
        
        /// <summary>
        /// ucMemberHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.MemberHeader ucMemberHeader;
        
        /// <summary>
        /// ucAutopeopleEmployerHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.Verticals.AutopeopleEmployerHeader ucAutopeopleEmployerHeader;
        
        /// <summary>
        /// ucOtdEmployerHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.Verticals.OtdEmployerHeader ucOtdEmployerHeader;
        
        /// <summary>
        /// ucVecciEmployerHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.Verticals.VecciEmployerHeader ucVecciEmployerHeader;
        
        /// <summary>
        /// ucSharedEmployerHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.Verticals.SharedEmployerHeader ucSharedEmployerHeader;
        
        /// <summary>
        /// ucEmployerHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.EmployerHeader ucEmployerHeader;
        
        /// <summary>
        /// ucAdministratorHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.AdministratorHeader ucAdministratorHeader;
        
        /// <summary>
        /// ucCustodianHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkMe.Web.UI.Controls.Common.Navs.CustodianHeader ucCustodianHeader;
    }
}
