//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Apps.Presentation.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkMe.Apps.Presentation.Errors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job has already been applied for..
        /// </summary>
        internal static string AlreadyAppliedException {
            get {
                return ResourceManager.GetString("AlreadyAppliedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already logged in..
        /// </summary>
        internal static string AlreadyAuthorizedException {
            get {
                return ResourceManager.GetString("AlreadyAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please try again..
        /// </summary>
        internal static string AuthenticationFailedException {
            get {
                return ResourceManager.GetString("AuthenticationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credit card number.
        /// </summary>
        internal static string cardnumber {
            get {
                return ResourceManager.GetString("cardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the packs must be chosen..
        /// </summary>
        internal static string ChooseProductException {
            get {
                return ResourceManager.GetString("ChooseProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the {0} will result in a circular dependency..
        /// </summary>
        internal static string CircularValidationError {
            get {
                return ResourceManager.GetString("CircularValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon has already expired and is no longer valid..
        /// </summary>
        internal static string CouponExpiredException {
            get {
                return ResourceManager.GetString("CouponExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon code cannot be found. Please confirm you&apos;ve typed it in correctly..
        /// </summary>
        internal static string CouponNotFoundException {
            get {
                return ResourceManager.GetString("CouponNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon does not apply to the type of products you&apos;ve ordered..
        /// </summary>
        internal static string CouponProductException {
            get {
                return ResourceManager.GetString("CouponProductException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon code is not valid for your account. Please login as a different user or user another coupon code..
        /// </summary>
        internal static string CouponRedeemerException {
            get {
                return ResourceManager.GetString("CouponRedeemerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please authorise the credit card charge..
        /// </summary>
        internal static string CreditCardAuthorisationValidationError {
            get {
                return ResourceManager.GetString("CreditCardAuthorisationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security code.
        /// </summary>
        internal static string cvv {
            get {
                return ResourceManager.GetString("cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salary.
        /// </summary>
        internal static string desiredsalarylowerbound {
            get {
                return ResourceManager.GetString("desiredsalarylowerbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} and {1} must match..
        /// </summary>
        internal static string DifferentValidationError {
            get {
                return ResourceManager.GetString("DifferentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is already being used..
        /// </summary>
        internal static string DuplicateUserException {
            get {
                return ResourceManager.GetString("DuplicateUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is already being used..
        /// </summary>
        internal static string DuplicateValidationError {
            get {
                return ResourceManager.GetString("DuplicateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} host name is not recognised..
        /// </summary>
        internal static string EmailAddressHostValidationError {
            get {
                return ResourceManager.GetString("EmailAddressHostValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} is invalid..
        /// </summary>
        internal static string EnumValueValidationError {
            get {
                return ResourceManager.GetString("EnumValueValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the file exceeds the maximum allowed of {0}MB..
        /// </summary>
        internal static string FileTooLargeException {
            get {
                return ResourceManager.GetString("FileTooLargeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} appears to have some script in it..
        /// </summary>
        internal static string HtmlValidationError {
            get {
                return ResourceManager.GetString("HtmlValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need {0} credit{1} to perform this action but you{2} have {3} available..
        /// </summary>
        internal static string InsufficientCreditsException {
            get {
                return ResourceManager.GetString("InsufficientCreditsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name &apos;{0}&apos; is not supported, as it must have one of the following extensions, {1}..
        /// </summary>
        internal static string InvalidFileNameException {
            get {
                return ResourceManager.GetString("InvalidFileNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo extension &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string InvalidPhotoExtensionException {
            get {
                return ResourceManager.GetString("InvalidPhotoExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our system is unable to extract your profile information from this file. Please try another document or create your profile manually..
        /// </summary>
        internal static string InvalidResumeException {
            get {
                return ResourceManager.GetString("InvalidResumeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resume extension &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string InvalidResumeExtensionException {
            get {
                return ResourceManager.GetString("InvalidResumeExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be empty..
        /// </summary>
        internal static string IsNotEmptyValidationError {
            get {
                return ResourceManager.GetString("IsNotEmptyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job ad expiry date cannot be later than {0} days from now..
        /// </summary>
        internal static string JobAdExpiryValidationError {
            get {
                return ResourceManager.GetString("JobAdExpiryValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        internal static string joinconfirmpassword {
            get {
                return ResourceManager.GetString("joinconfirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string joinloginid {
            get {
                return ResourceManager.GetString("joinloginid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string joinpassword {
            get {
                return ResourceManager.GetString("joinpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {1} and {2} characters in length..
        /// </summary>
        internal static string LengthRangeValidationError {
            get {
                return ResourceManager.GetString("LengthRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be {1} characters in length..
        /// </summary>
        internal static string LengthValidationError {
            get {
                return ResourceManager.GetString("LengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string loginid {
            get {
                return ResourceManager.GetString("loginid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string loginloginid {
            get {
                return ResourceManager.GetString("loginloginid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string loginpassword {
            get {
                return ResourceManager.GetString("loginpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be no more than {1} characters in length..
        /// </summary>
        internal static string MaximumLengthValidationError {
            get {
                return ResourceManager.GetString("MaximumLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} characters in length..
        /// </summary>
        internal static string MinimumLengthValidationError {
            get {
                return ResourceManager.GetString("MinimumLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resume cannot be found..
        /// </summary>
        internal static string NoResumeException {
            get {
                return ResourceManager.GetString("NoResumeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resume file cannot be found..
        /// </summary>
        internal static string NoResumeFileException {
            get {
                return ResourceManager.GetString("NoResumeFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new {0} needs to be different from its original value..
        /// </summary>
        internal static string NotChangedValidationError {
            get {
                return ResourceManager.GetString("NotChangedValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be found..
        /// </summary>
        internal static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with value &apos;{1}&apos; cannot be found..
        /// </summary>
        internal static string NotFoundValidationError {
            get {
                return ResourceManager.GetString("NotFoundValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The candidate details have been hidden by the candidate..
        /// </summary>
        internal static string NotVisibleException {
            get {
                return ResourceManager.GetString("NotVisibleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be less than or equal to {1}..
        /// </summary>
        internal static string NumericMaximumValueValidationError {
            get {
                return ResourceManager.GetString("NumericMaximumValueValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string NumericMinimumValueValidationError {
            get {
                return ResourceManager.GetString("NumericMinimumValueValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {1} and {2}..
        /// </summary>
        internal static string NumericValueRangeValidationError {
            get {
                return ResourceManager.GetString("NumericValueRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our system is unable to extract your profile information from this file at this time. Please try again later or create your profile manually. We apologise for the inconvenience..
        /// </summary>
        internal static string ParserUnavailableException {
            get {
                return ResourceManager.GetString("ParserUnavailableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permissions..
        /// </summary>
        internal static string PermissionsException {
            get {
                return ResourceManager.GetString("PermissionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be a valid postal location..
        /// </summary>
        internal static string PostalSuburbValidationError {
            get {
                return ResourceManager.GetString("PostalSuburbValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credit card could not be processed: {0}.
        /// </summary>
        internal static string PurchaseUserException {
            get {
                return ResourceManager.GetString("PurchaseUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {1} and {2} characters in length and not have any invalid characters..
        /// </summary>
        internal static string RegexLengthRangeValidationError {
            get {
                return ResourceManager.GetString("RegexLengthRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be {1} characters in length and not have any invalid characters..
        /// </summary>
        internal static string RegexLengthValidationError {
            get {
                return ResourceManager.GetString("RegexLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be valid and have less than {1} characters..
        /// </summary>
        internal static string RegexMaximumLengthValidationError {
            get {
                return ResourceManager.GetString("RegexMaximumLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} characters in length and not have any invalid characters..
        /// </summary>
        internal static string RegexMinimumLengthValidationError {
            get {
                return ResourceManager.GetString("RegexMinimumLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must not have any invalid characters..
        /// </summary>
        internal static string RegexValidationError {
            get {
                return ResourceManager.GetString("RegexValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        internal static string RequiredValidationError {
            get {
                return ResourceManager.GetString("RequiredValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salary.
        /// </summary>
        internal static string salarylowerbound {
            get {
                return ResourceManager.GetString("salarylowerbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower and upper bounds for the {0} must not be negative..
        /// </summary>
        internal static string SalaryValidationError {
            get {
                return ResourceManager.GetString("SalaryValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in the LinkMe website. We apologise for the inconvenience..
        /// </summary>
        internal static string ServerErrorException {
            get {
                return ResourceManager.GetString("ServerErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to availability.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms and conditions..
        /// </summary>
        internal static string TermsValidationError {
            get {
                return ResourceManager.GetString("TermsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call LinkMe on 1800 546-563 to contact additional candidates..
        /// </summary>
        internal static string TooManyAccessesException {
            get {
                return ResourceManager.GetString("TooManyAccessesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call LinkMe on 1800 546-563 to post more job ads..
        /// </summary>
        internal static string TooManyJobAdsException {
            get {
                return ResourceManager.GetString("TooManyJobAdsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total size of all files exceeds the maximum allowed of {0}MB..
        /// </summary>
        internal static string TotalFilesTooLargeException {
            get {
                return ResourceManager.GetString("TotalFilesTooLargeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not logged in..
        /// </summary>
        internal static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string UrlNotFoundException {
            get {
                return ResourceManager.GetString("UrlNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is disabled..
        /// </summary>
        internal static string UserDisabledException {
            get {
                return ResourceManager.GetString("UserDisabledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must change their password..
        /// </summary>
        internal static string UserMustChangePasswordException {
            get {
                return ResourceManager.GetString("UserMustChangePasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors found:.
        /// </summary>
        internal static string ValidationErrorsException {
            get {
                return ResourceManager.GetString("ValidationErrorsException", resourceCulture);
            }
        }
    }
}
