namespace LinkMe.Framework.Utility.Win32
{
	// Win32 API enumerations.

	public enum REGKIND
	{
		REGKIND_DEFAULT,
		REGKIND_REGISTER,
		REGKIND_NONE
	}

	public enum VARKIND
	{
		VAR_PERINSTANCE = 0,
		VAR_STATIC = 1,
		VAR_CONST = 2,
		VAR_DISPATCH = 3
	}

	[System.Flags]
	public enum CLSCTX
	{
		CLSCTX_INPROC_SERVER        = 0x1,
		CLSCTX_INPROC_HANDLER       = 0x2,
		CLSCTX_LOCAL_SERVER         = 0x4,
		CLSCTX_INPROC_SERVER16      = 0x8,
		CLSCTX_REMOTE_SERVER        = 0x10,
		CLSCTX_INPROC_HANDLER16     = 0x20,
		CLSCTX_NO_CODE_DOWNLOAD     = 0x400,
		CLSCTX_NO_CUSTOM_MARSHAL    = 0x1000,
		CLSCTX_ENABLE_CODE_DOWNLOAD = 0x2000,
		CLSCTX_NO_FAILURE_LOG       = 0x4000,
		CLSCTX_DISABLE_AAA          = 0x8000,
		CLSCTX_ENABLE_AAA           = 0x10000,
		CLSCTX_FROM_DEFAULT_CONTEXT = 0x20000,
		CLSCTX_INPROC               = CLSCTX_INPROC_SERVER | CLSCTX_INPROC_HANDLER,
		CLSCTX_SERVER               = CLSCTX_INPROC_SERVER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER,
		CLSCTX_ALL                  = CLSCTX_SERVER | CLSCTX_INPROC_HANDLER,
	}

	[System.Flags]
	public enum REGCLS
	{
		REGCLS_SINGLEUSE         = 0, 
		REGCLS_MULTIPLEUSE       = 1, 
		REGCLS_MULTI_SEPARATE    = 2, 
		REGCLS_SUSPENDED         = 4, 
		REGCLS_SURROGATE         = 8, 
	}

	[System.Flags]
	public enum WBEM_COMPILER_OPTIONS
	{
		None						= 0,
		WBEM_FLAG_CHECK_ONLY		= 0x1,
		WBEM_FLAG_AUTORECOVER		= 0x2,
		WBEM_FLAG_WMI_CHECK			= 0x4,
		WBEM_FLAG_CONSOLE_PRINT		= 0x8,
		WBEM_FLAG_DONT_ADD_TO_LIST	= 0x10,
		WBEM_FLAG_SPLIT_FILES		= 0x20,
		WBEM_FLAG_STORE_FILE		= 0x100
	}

	public enum RPC_C_AUTHN_LEVEL
	{
		DEFAULT						= 0,
		NONE						= 1,
		CONNECT						= 2,
		CALL						= 3,
		PKT							= 4,
		INTEGRITY					= 5,
		PRIVACY						= 6
	}

	public enum RPC_C_IMP_LEVEL
	{
		DEFAULT						= 0,
		ANONYMOUS					= 1,
		IDENTIFY					= 2,
		IMPERSONATE					= 3,
		DELEGATE					= 4
	}

	[System.Flags]
	public enum OLEMISC
	{
		RECOMPOSEONRESIZE				= 0x1,
		ONLYICONIC						= 0x2,
		INSERTNOTREPLACE				= 0x4,
		STATIC							= 0x8,
		CANTLINKINSIDE					= 0x10,
		CANLINKBYOLE1					= 0x20,
		ISLINKOBJECT					= 0x40,
		INSIDEOUT						= 0x80,
		ACTIVATEWHENVISIBLE				= 0x100,
		RENDERINGISDEVICEINDEPENDENT	= 0x200,
		INVISIBLEATRUNTIME				= 0x400,
		ALWAYSRUN						= 0x800,
		ACTSLIKEBUTTON					= 0x1000,
		ACTSLIKELABEL					= 0x2000,
		NOUIACTIVATE					= 0x4000,
		ALIGNABLE						= 0x8000,
		SIMPLEFRAME						= 0x10000,
		SETCLIENTSITEFIRST				= 0x20000,
		IMEMODE							= 0x40000,
		IGNOREACTIVATEWHENVISIBLE		= 0x80000,
		WANTSTOMENUMERGE				= 0x100000,
		SUPPORTSMULTILEVELUNDO			= 0x200000
	}
}
