insert into namedlocation values (6000, 'Adelaide (All Adelaide)')
insert into namedlocation values (6001, 'Brisbane (All Brisbane)')
insert into namedlocation values (6002, 'Brisbane (Bayside & Eastern Suburbs)')
insert into namedlocation values (6003, 'Brisbane (CBD & Inner Suburbs)')
insert into namedlocation values (6004, 'Brisbane (Northern Brisbane)')
insert into namedlocation values (6005, 'Brisbane (Northern Suburbs)')
insert into namedlocation values (6006, 'Brisbane (Southern Suburbs & Logan)')
insert into namedlocation values (6007, 'Brisbane (Western Suburbs & Ipswich)')
insert into namedlocation values (6008, 'Canberra (All Canberra)')
insert into namedlocation values (6009, 'Darwin (All Darwin)')
insert into namedlocation values (6010, 'Gold Coast (All Gold Coast)')
insert into namedlocation values (6011, 'Hobart (All Hobart)')
insert into namedlocation values (6012, 'Melbourne (All Melbourne)')
insert into namedlocation values (6013, 'Melbourne (Bayside & South Eastern Suburbs)')
insert into namedlocation values (6014, 'Melbourne (CBD & Inner Suburbs)')
insert into namedlocation values (6015, 'Melbourne (Eastern Suburbs)')
insert into namedlocation values (6016, 'Melbourne (Northern Suburbs)')
insert into namedlocation values (6017, 'Melbourne (Western Suburbs)')
insert into namedlocation values (6018, 'Perth (All Perth)')
insert into namedlocation values (6019, 'Perth (CBD, Inner & Western Suburbs)')
insert into namedlocation values (6020, 'Perth (Eastern Suburbs)')
insert into namedlocation values (6021, 'Perth (Fremantle & Southern Suburbs)')
insert into namedlocation values (6022, 'Perth (Northern Suburbs & Joondalup)')
insert into namedlocation values (6023, 'Perth (Rockingham & Kwinana)')
insert into namedlocation values (6024, 'Regional ACT (All ACT)')
insert into namedlocation values (6025, 'Regional NSW (Albury, Wodonga & Murray)')
insert into namedlocation values (6026, 'Regional NSW (All Regional New South Wales)')
insert into namedlocation values (6027, 'Regional NSW (Blue Mountains & Central West)')
insert into namedlocation values (6028, 'Regional NSW (Coffs Harbour & North Coast)')
insert into namedlocation values (6029, 'Regional NSW (Dubbo & Central NSW)')
insert into namedlocation values (6030, 'Regional NSW (Far West & North Central NSW)')
insert into namedlocation values (6031, 'Regional NSW (Gosford & Central Coast)')
insert into namedlocation values (6032, 'Regional NSW (Goulburn & Southern Tablelands)')
insert into namedlocation values (6033, 'Regional NSW (Lismore & Far North Coast)')
insert into namedlocation values (6034, 'Regional NSW (Newcastle, Maitland & Hunter)')
insert into namedlocation values (6035, 'Regional NSW (Port Macquarie & Mid North Coast)')
insert into namedlocation values (6036, 'Regional NSW (Richmond & Hawkesbury)')
insert into namedlocation values (6037, 'Regional NSW (Tamworth & North West NSW)')
insert into namedlocation values (6038, 'Regional NSW (Tumut, Southern Highlands & Snowy)')
insert into namedlocation values (6039, 'Regional NSW (Wagga Wagga & Riverina)')
insert into namedlocation values (6040, 'Regional NSW (Wollongong, Illawarra and South Coast)')
insert into namedlocation values (6041, 'Regional NT (Alice Springs & Central Australia)')
insert into namedlocation values (6042, 'Regional NT (All Regional NT)')
insert into namedlocation values (6043, 'Regional NT (Katherine & Northern Australia)')
insert into namedlocation values (6044, 'Regional QLD (All Regional Queensland)')
insert into namedlocation values (6045, 'Regional QLD (Bundaberg & Wide Bay Burnett)')
insert into namedlocation values (6046, 'Regional QLD (Cairns & Far North)')
insert into namedlocation values (6047, 'Regional QLD (Gladstone & Central QLD)')
insert into namedlocation values (6048, 'Regional QLD (Hervey Bay & Fraser Coast)')
insert into namedlocation values (6049, 'Regional QLD (Mackay & Coalfields)')
insert into namedlocation values (6050, 'Regional QLD (Mt Isa & Western QLD)')
insert into namedlocation values (6051, 'Regional QLD (Rockhampton & Capricorn Coast)')
insert into namedlocation values (6052, 'Regional QLD (Somerset & Lockyer)')
insert into namedlocation values (6053, 'Regional QLD (Sunshine Coast)')
insert into namedlocation values (6054, 'Regional QLD (Toowoomba & Darling Downs)')
insert into namedlocation values (6055, 'Regional QLD (Townsville & Northern QLD)')
insert into namedlocation values (6056, 'Regional SA (Adelaide Hills & Barossa)')
insert into namedlocation values (6057, 'Regional SA (All Regional South Australia)')
insert into namedlocation values (6058, 'Regional SA (Coober Pedy & Outback SA)')
insert into namedlocation values (6059, 'Regional SA (Fleurieu Peninsular & Kangaroo Island)')
insert into namedlocation values (6060, 'Regional SA (Mt Gambier & Limestone Coast)')
insert into namedlocation values (6061, 'Regional SA (Riverland & Murray Mallee)')
insert into namedlocation values (6062, 'Regional SA (Whyalla & Eyre Peninsula)')
insert into namedlocation values (6063, 'Regional SA (Yorke Peninsula & Clare Valley)')
insert into namedlocation values (6064, 'Regional TAS (All TAS)')
insert into namedlocation values (6065, 'Regional TAS (Central & South East)')
insert into namedlocation values (6066, 'Regional TAS (Devenport & North West)')
insert into namedlocation values (6067, 'Regional TAS (Launceston & North East)')
insert into namedlocation values (6068, 'Regional VIC (All Regional Victoria)')
insert into namedlocation values (6069, 'Regional VIC (Bairnsdale & Gippsland)')
insert into namedlocation values (6070, 'Regional VIC (Ballarat & Central Highlands)')
insert into namedlocation values (6071, 'Regional VIC (Bendigo, Goldfields & Macedon Ranges)')
insert into namedlocation values (6072, 'Regional VIC (Geelong & Great Ocean Road)')
insert into namedlocation values (6073, 'Regional VIC (Goulburn & Southern Tablelands)')
insert into namedlocation values (6074, 'Regional VIC (Horsham & Grampians)')
insert into namedlocation values (6075, 'Regional VIC (Mildura & Murray)')
insert into namedlocation values (6076, 'Regional VIC (Mornington Peninsula & Bass Coast)')
insert into namedlocation values (6077, 'Regional VIC (Shepparton & Goulburn Valley)')
insert into namedlocation values (6078, 'Regional VIC (Traralgon & La Trobe Valley)')
insert into namedlocation values (6079, 'Regional VIC (Yarra Valley & High Country)')
insert into namedlocation values (6080, 'Regional WA (Albany & Great Southern)')
insert into namedlocation values (6081, 'Regional WA (All Regional WA)')
insert into namedlocation values (6082, 'Regional WA (Broome & Kimberley)')
insert into namedlocation values (6083, 'Regional WA (Bunbury & South West)')
insert into namedlocation values (6084, 'Regional WA (Geraldton, Gascoyne & Mid West)')
insert into namedlocation values (6085, 'Regional WA (Kalgoorlie, Goldfields & Esperance)')
insert into namedlocation values (6086, 'Regional WA (Mandurah & Peel)')
insert into namedlocation values (6087, 'Regional WA (Northam & Wheatbelt)')
insert into namedlocation values (6088, 'Regional WA (Port Hedland, Karratha & Pilbara)')
insert into namedlocation values (6089, 'Sydney (All Sydney)')
insert into namedlocation values (6090, 'Sydney (CBD, Inner West & Eastern Suburbs)')
insert into namedlocation values (6091, 'Sydney (North Shore & Northern Beaches)')
insert into namedlocation values (6092, 'Sydney (North West & Hills District)')
insert into namedlocation values (6093, 'Sydney (Parramatta & Western Suburbs)')
insert into namedlocation values (6094, 'Sydney (Ryde & Macquarie Park)')
insert into namedlocation values (6095, 'Sydney (South West & M5 Corridor)')
insert into namedlocation values (6096, 'Sydney (Southern Suburbs & Sutherland Shire)')

insert into geographicalarea values (6000)
insert into geographicalarea values (6001)
insert into geographicalarea values (6002)
insert into geographicalarea values (6003)
insert into geographicalarea values (6004)
insert into geographicalarea values (6005)
insert into geographicalarea values (6006)
insert into geographicalarea values (6007)
insert into geographicalarea values (6008)
insert into geographicalarea values (6009)
insert into geographicalarea values (6010)
insert into geographicalarea values (6011)
insert into geographicalarea values (6012)
insert into geographicalarea values (6013)
insert into geographicalarea values (6014)
insert into geographicalarea values (6015)
insert into geographicalarea values (6016)
insert into geographicalarea values (6017)
insert into geographicalarea values (6018)
insert into geographicalarea values (6019)
insert into geographicalarea values (6020)
insert into geographicalarea values (6021)
insert into geographicalarea values (6022)
insert into geographicalarea values (6023)
insert into geographicalarea values (6024)
insert into geographicalarea values (6025)
insert into geographicalarea values (6026)
insert into geographicalarea values (6027)
insert into geographicalarea values (6028)
insert into geographicalarea values (6029)
insert into geographicalarea values (6030)
insert into geographicalarea values (6031)
insert into geographicalarea values (6032)
insert into geographicalarea values (6033)
insert into geographicalarea values (6034)
insert into geographicalarea values (6035)
insert into geographicalarea values (6036)
insert into geographicalarea values (6037)
insert into geographicalarea values (6038)
insert into geographicalarea values (6039)
insert into geographicalarea values (6040)
insert into geographicalarea values (6041)
insert into geographicalarea values (6042)
insert into geographicalarea values (6043)
insert into geographicalarea values (6044)
insert into geographicalarea values (6045)
insert into geographicalarea values (6046)
insert into geographicalarea values (6047)
insert into geographicalarea values (6048)
insert into geographicalarea values (6049)
insert into geographicalarea values (6050)
insert into geographicalarea values (6051)
insert into geographicalarea values (6052)
insert into geographicalarea values (6053)
insert into geographicalarea values (6054)
insert into geographicalarea values (6055)
insert into geographicalarea values (6056)
insert into geographicalarea values (6057)
insert into geographicalarea values (6058)
insert into geographicalarea values (6059)
insert into geographicalarea values (6060)
insert into geographicalarea values (6061)
insert into geographicalarea values (6062)
insert into geographicalarea values (6063)
insert into geographicalarea values (6064)
insert into geographicalarea values (6065)
insert into geographicalarea values (6066)
insert into geographicalarea values (6067)
insert into geographicalarea values (6068)
insert into geographicalarea values (6069)
insert into geographicalarea values (6070)
insert into geographicalarea values (6071)
insert into geographicalarea values (6072)
insert into geographicalarea values (6073)
insert into geographicalarea values (6074)
insert into geographicalarea values (6075)
insert into geographicalarea values (6076)
insert into geographicalarea values (6077)
insert into geographicalarea values (6078)
insert into geographicalarea values (6079)
insert into geographicalarea values (6080)
insert into geographicalarea values (6081)
insert into geographicalarea values (6082)
insert into geographicalarea values (6083)
insert into geographicalarea values (6084)
insert into geographicalarea values (6085)
insert into geographicalarea values (6086)
insert into geographicalarea values (6087)
insert into geographicalarea values (6088)
insert into geographicalarea values (6089)
insert into geographicalarea values (6090)
insert into geographicalarea values (6091)
insert into geographicalarea values (6092)
insert into geographicalarea values (6093)
insert into geographicalarea values (6094)
insert into geographicalarea values (6095)
insert into geographicalarea values (6096)

insert into region values (6000, 'Adelaide-All-Adelaide', 0)
insert into region values (6001, 'Brisbane-All-Brisbane', 0)
insert into region values (6002, 'Brisbane-Bayside-Eastern-Suburbs', 0)
insert into region values (6003, 'Brisbane-CBD-Inner-Suburbs', 0)
insert into region values (6004, 'Brisbane-Northern-Brisbane', 0)
insert into region values (6005, 'Brisbane-Northern-Suburbs', 0)
insert into region values (6006, 'Brisbane-Southern-Suburbs-Logan', 0)
insert into region values (6007, 'Brisbane-Western-Suburbs-Ipswich', 0)
insert into region values (6008, 'Canberra-All-Canberra', 0)
insert into region values (6009, 'Darwin-All-Darwin', 0)
insert into region values (6010, 'Gold-Coast-All-Gold-Coast', 0)
insert into region values (6011, 'Hobart-All-Hobart', 0)
insert into region values (6012, 'Melbourne-All-Melbourne', 0)
insert into region values (6013, 'Melbourne-Bayside-South-Eastern-Suburbs', 0)
insert into region values (6014, 'Melbourne-CBD-Inner-Suburbs', 0)
insert into region values (6015, 'Melbourne-Eastern-Suburbs', 0)
insert into region values (6016, 'Melbourne-Northern-Suburbs', 0)
insert into region values (6017, 'Melbourne-Western-Suburbs', 0)
insert into region values (6018, 'Perth-All-Perth', 0)
insert into region values (6019, 'Perth-CBD,-Inner-Western-Suburbs', 0)
insert into region values (6020, 'Perth-Eastern-Suburbs', 0)
insert into region values (6021, 'Perth-Fremantle-Southern-Suburbs', 0)
insert into region values (6022, 'Perth-Northern-Suburbs-Joondalup', 0)
insert into region values (6023, 'Perth-Rockingham-Kwinana', 0)
insert into region values (6024, 'Regional-ACT-All-ACT', 0)
insert into region values (6025, 'Regional-NSW-Albury,-Wodonga-Murray', 0)
insert into region values (6026, 'Regional-NSW-All-Regional-New-South-Wales', 0)
insert into region values (6027, 'Regional-NSW-Blue-Mountains-Central-West', 0)
insert into region values (6028, 'Regional-NSW-Coffs-Harbour-North-Coast', 0)
insert into region values (6029, 'Regional-NSW-Dubbo-Central-NSW', 0)
insert into region values (6030, 'Regional-NSW-Far-West-North-Central-NSW', 0)
insert into region values (6031, 'Regional-NSW-Gosford-Central-Coast', 0)
insert into region values (6032, 'Regional-NSW-Goulburn-Southern-Tablelands', 0)
insert into region values (6033, 'Regional-NSW-Lismore-Far-North-Coast', 0)
insert into region values (6034, 'Regional-NSW-Newcastle,-Maitland-Hunter', 0)
insert into region values (6035, 'Regional-NSW-Port-Macquarie-Mid-North-Coast', 0)
insert into region values (6036, 'Regional-NSW-Richmond-Hawkesbury', 0)
insert into region values (6037, 'Regional-NSW-Tamworth-North-West-NSW', 0)
insert into region values (6038, 'Regional-NSW-Tumut,-Southern-Highlands-Snowy', 0)
insert into region values (6039, 'Regional-NSW-Wagga-Wagga-Riverina', 0)
insert into region values (6040, 'Regional-NSW-Wollongong,-Illawarra-and-South-Coast', 0)
insert into region values (6041, 'Regional-NT-Alice-Springs-Central-Australia', 0)
insert into region values (6042, 'Regional-NT-All-Regional-NT', 0)
insert into region values (6043, 'Regional-NT-Katherine-Northern-Australia', 0)
insert into region values (6044, 'Regional-QLD-All-Regional-Queensland', 0)
insert into region values (6045, 'Regional-QLD-Bundaberg-Wide-Bay-Burnett', 0)
insert into region values (6046, 'Regional-QLD-Cairns-Far-North', 0)
insert into region values (6047, 'Regional-QLD-Gladstone-Central-QLD', 0)
insert into region values (6048, 'Regional-QLD-Hervey-Bay-Fraser-Coast', 0)
insert into region values (6049, 'Regional-QLD-Mackay-Coalfields', 0)
insert into region values (6050, 'Regional-QLD-Mt-Isa-Western-QLD', 0)
insert into region values (6051, 'Regional-QLD-Rockhampton-Capricorn-Coast', 0)
insert into region values (6052, 'Regional-QLD-Somerset-Lockyer', 0)
insert into region values (6053, 'Regional-QLD-Sunshine-Coast', 0)
insert into region values (6054, 'Regional-QLD-Toowoomba-Darling-Downs', 0)
insert into region values (6055, 'Regional-QLD-Townsville-Northern-QLD', 0)
insert into region values (6056, 'Regional-SA-Adelaide-Hills-Barossa', 0)
insert into region values (6057, 'Regional-SA-All-Regional-South-Australia', 0)
insert into region values (6058, 'Regional-SA-Coober-Pedy-Outback-SA', 0)
insert into region values (6059, 'Regional-SA-Fleurieu-Peninsular-Kangaroo-Island', 0)
insert into region values (6060, 'Regional-SA-Mt-Gambier-Limestone-Coast', 0)
insert into region values (6061, 'Regional-SA-Riverland-Murray-Mallee', 0)
insert into region values (6062, 'Regional-SA-Whyalla-Eyre-Peninsula', 0)
insert into region values (6063, 'Regional-SA-Yorke-Peninsula-Clare-Valley', 0)
insert into region values (6064, 'Regional-TAS-All-TAS', 0)
insert into region values (6065, 'Regional-TAS-Central-South-East', 0)
insert into region values (6066, 'Regional-TAS-Devenport-North-West', 0)
insert into region values (6067, 'Regional-TAS-Launceston-North-East', 0)
insert into region values (6068, 'Regional-VIC-All-Regional-Victoria', 0)
insert into region values (6069, 'Regional-VIC-Bairnsdale-Gippsland', 0)
insert into region values (6070, 'Regional-VIC-Ballarat-Central-Highlands', 0)
insert into region values (6071, 'Regional-VIC-Bendigo,-Goldfields-Macedon-Ranges', 0)
insert into region values (6072, 'Regional-VIC-Geelong-Great-Ocean-Road', 0)
insert into region values (6073, 'Regional-VIC-Goulburn-Southern-Tablelands', 0)
insert into region values (6074, 'Regional-VIC-Horsham-Grampians', 0)
insert into region values (6075, 'Regional-VIC-Mildura-Murray', 0)
insert into region values (6076, 'Regional-VIC-Mornington-Peninsula-Bass-Coast', 0)
insert into region values (6077, 'Regional-VIC-Shepparton-Goulburn-Valley', 0)
insert into region values (6078, 'Regional-VIC-Traralgon-La-Trobe-Valley', 0)
insert into region values (6079, 'Regional-VIC-Yarra-Valley-High-Country', 0)
insert into region values (6080, 'Regional-WA-Albany-Great-Southern', 0)
insert into region values (6081, 'Regional-WA-All-Regional-WA', 0)
insert into region values (6082, 'Regional-WA-Broome-Kimberley', 0)
insert into region values (6083, 'Regional-WA-Bunbury-South-West', 0)
insert into region values (6084, 'Regional-WA-Geraldton,-Gascoyne-Mid-West', 0)
insert into region values (6085, 'Regional-WA-Kalgoorlie,-Goldfields-Esperance', 0)
insert into region values (6086, 'Regional-WA-Mandurah-Peel', 0)
insert into region values (6087, 'Regional-WA-Northam-Wheatbelt', 0)
insert into region values (6088, 'Regional-WA-Port-Hedland,-Karratha-Pilbara', 0)
insert into region values (6089, 'Sydney-All-Sydney', 0)
insert into region values (6090, 'Sydney-CBD,-Inner-West-Eastern-Suburbs', 0)
insert into region values (6091, 'Sydney-North-Shore-Northern-Beaches', 0)
insert into region values (6092, 'Sydney-North-West-Hills-District', 0)
insert into region values (6093, 'Sydney-Parramatta-Western-Suburbs', 0)
insert into region values (6094, 'Sydney-Ryde-Macquarie-Park', 0)
insert into region values (6095, 'Sydney-South-West-M5-Corridor', 0)
insert into region values (6096, 'Sydney-Southern-Suburbs-Sutherland-Shire', 0)
