--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 6.5.799
--   Created On : Tuesday, 12 December, 2006 
--   DBMS       : SQL Server 2000 
--   -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('[linkme_owner].[AtsIntegrator]') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE [linkme_owner].[AtsIntegrator]
GO

CREATE TABLE [linkme_owner].[AtsIntegrator] ( 
	[id] uniqueidentifier NOT NULL,
	[name] nvarchar(100) NOT NULL
)
GO

ALTER TABLE [linkme_owner].[AtsIntegrator]
	ADD CONSTRAINT [UQ_AtsIntegrator_name] UNIQUE ([name])
GO

ALTER TABLE [linkme_owner].[AtsIntegrator] ADD CONSTRAINT [PK_AtsIntegrator] 
	PRIMARY KEY CLUSTERED ([id])
GO



