--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.817
--  Created On : Monday, 29 October, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('FileData') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FileData
GO

CREATE TABLE FileData ( 
	id uniqueidentifier NOT NULL,
	context FileContext NOT NULL,
	extension nvarchar(255) NOT NULL,
	hash binary(16) NOT NULL,
	sizeBytes int NOT NULL
)
GO

ALTER TABLE FileData ADD CONSTRAINT PK_FileData 
	PRIMARY KEY CLUSTERED (id)
GO
