--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.817
--  Created On : Monday, 22 October, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('UserToUserRequest') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE UserToUserRequest
GO

CREATE TABLE UserToUserRequest ( 
	id uniqueidentifier NOT NULL,
	actionedTime datetime NULL,
	firstSentTime datetime NULL,
	flags RequestFlags NOT NULL,
	lastSentTime datetime NULL,
	messageText MessageText NULL,
	status RequestStatus NOT NULL
)
GO

ALTER TABLE UserToUserRequest ADD CONSTRAINT PK_UserToUserRequest 
	PRIMARY KEY CLUSTERED (id)
GO








