--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.0.813
--   Created On : Thursday, 12 July, 2007 
--   DBMS       : SQL Server 2000 
--   -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('UserMessage') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE UserMessage
GO

CREATE TABLE UserMessage ( 
	id uniqueidentifier NOT NULL,
	sentTime datetime NOT NULL,
	text MessageText NOT NULL,
	senderId uniqueidentifier NOT NULL,
	threadId uniqueidentifier NOT NULL
)
GO

ALTER TABLE UserMessage ADD CONSTRAINT PK_UserMessage 
	PRIMARY KEY CLUSTERED (id)
GO

ALTER TABLE UserMessage ADD CONSTRAINT FK_UserMessage_MessageThread 
	FOREIGN KEY (threadId) REFERENCES MessageThread (id)
GO

ALTER TABLE UserMessage ADD CONSTRAINT FK_UserMessage_SenderUser 
	FOREIGN KEY (senderId) REFERENCES RegisteredUser (id)
GO






