--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.816
--  Created On : Thursday, 06 September, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('UserEventExtraData') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE UserEventExtraData
GO

CREATE TABLE UserEventExtraData ( 
	eventId uniqueidentifier NOT NULL,
	[key] varchar(20) NOT NULL,
	value nvarchar(1000) NOT NULL
)
GO

ALTER TABLE UserEventExtraData ADD CONSTRAINT PK_UserEventExtraData 
	PRIMARY KEY CLUSTERED (eventId, [key])
GO

ALTER TABLE UserEventExtraData ADD CONSTRAINT FK_UserEventExtraData_UserEvent 
	FOREIGN KEY (eventId) REFERENCES UserEvent (id)
GO




