--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.813
--  Created On : Friday, 13 July, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('JobAdArea') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE JobAdArea
GO

CREATE TABLE JobAdArea ( 
	jobAdId uniqueidentifier NOT NULL,
	areaId int NOT NULL
)
GO

ALTER TABLE JobAdArea ADD CONSTRAINT PK_JobAdArea 
	PRIMARY KEY CLUSTERED (jobAdId, areaId)
GO

ALTER TABLE JobAdArea ADD CONSTRAINT FK_JobAdArea_GeographicalArea 
	FOREIGN KEY (areaId) REFERENCES GeographicalArea (id)
GO

ALTER TABLE JobAdArea ADD CONSTRAINT FK_JobAdArea_JobAd 
	FOREIGN KEY (jobAdId) REFERENCES JobAd (id)
GO



