--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.817
--  Created On : Tuesday, 23 October, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('UserMessageAttachment') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE UserMessageAttachment
GO

CREATE TABLE UserMessageAttachment ( 
	messageId uniqueidentifier NOT NULL,
	fileId uniqueidentifier NOT NULL
)
GO

ALTER TABLE UserMessageAttachment ADD CONSTRAINT PK_UserMessageAttachment 
	PRIMARY KEY CLUSTERED (messageId, fileId)
GO

ALTER TABLE UserMessageAttachment ADD CONSTRAINT FK_UserMessageAttachment_FileReference 
	FOREIGN KEY (fileId) REFERENCES FileReference (id)
GO

ALTER TABLE UserMessageAttachment ADD CONSTRAINT FK_UserMessageAttachment_UserMessage 
	FOREIGN KEY (messageId) REFERENCES UserMessage (id)
GO



