--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.0.813
--   Created On : Thursday, 12 July, 2007 
--   DBMS       : SQL Server 2000 
--   -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('NetworkLink') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE NetworkLink
GO

CREATE TABLE NetworkLink ( 
	fromNetworkerId uniqueidentifier NOT NULL,
	toNetworkerId uniqueidentifier NOT NULL,
	addedTime datetime NOT NULL
)
GO

ALTER TABLE NetworkLink ADD CONSTRAINT PK_NetworkLink 
	PRIMARY KEY CLUSTERED (fromNetworkerId, toNetworkerId)
GO

ALTER TABLE NetworkLink ADD CONSTRAINT FK_NetworkLink_FromNetworker 
	FOREIGN KEY (fromNetworkerId) REFERENCES Networker (id)
GO

ALTER TABLE NetworkLink ADD CONSTRAINT FK_NetworkLink_ToNetworker 
	FOREIGN KEY (toNetworkerId) REFERENCES Networker (id)
GO




