--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.0.813
--   Created On : Thursday, 12 July, 2007 
--   DBMS       : SQL Server 2000 
--   -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('UserEventActionedJobAd') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE UserEventActionedJobAd
GO

CREATE TABLE UserEventActionedJobAd ( 
	eventId uniqueidentifier NOT NULL,
	jobAdId uniqueidentifier NOT NULL
)
GO

ALTER TABLE UserEventActionedJobAd ADD CONSTRAINT PK_UserEventActionedJobAd 
	PRIMARY KEY CLUSTERED (eventId)
GO

ALTER TABLE UserEventActionedJobAd ADD CONSTRAINT FK_UserEventActionedJobAd_JobAd 
	FOREIGN KEY (jobAdId) REFERENCES JobAd (id)
GO

ALTER TABLE UserEventActionedJobAd ADD CONSTRAINT FK_UserEventActionedJobAd_UserEvent 
	FOREIGN KEY (eventId) REFERENCES UserEvent (id)
GO



