--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.0.813
--   Created On : Thursday, 12 July, 2007 
--   DBMS       : SQL Server 2000 
--   -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('EmployerIndustry') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE EmployerIndustry
GO

CREATE TABLE EmployerIndustry ( 
	employerId uniqueidentifier NOT NULL,
	industryId uniqueidentifier NOT NULL
)
GO

ALTER TABLE EmployerIndustry ADD CONSTRAINT PK_EmployerIndustry 
	PRIMARY KEY CLUSTERED (employerId, industryId)
GO

ALTER TABLE EmployerIndustry ADD CONSTRAINT FK_EmployerIndustry_Employer 
	FOREIGN KEY (employerId) REFERENCES Employer (id)
GO

ALTER TABLE EmployerIndustry ADD CONSTRAINT FK_EmployerIndustry_Industry 
	FOREIGN KEY (industryId) REFERENCES Industry (id)
GO



