--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.814
--  Created On : Tuesday, 24 July, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('PostalSuburb') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PostalSuburb
GO

CREATE TABLE PostalSuburb ( 
	id int NOT NULL,
	displayName LocationDisplayName NOT NULL,
	postcodeId int NOT NULL,
	countrySubdivisionId int NOT NULL
)
GO

ALTER TABLE PostalSuburb ADD CONSTRAINT PK_PostalSuburb 
	PRIMARY KEY CLUSTERED (id)
GO

ALTER TABLE PostalSuburb ADD CONSTRAINT FK_PostalSuburb_CountrySubdivision 
	FOREIGN KEY (countrySubdivisionId) REFERENCES CountrySubdivision (id)
GO

ALTER TABLE PostalSuburb ADD CONSTRAINT FK_PostalSuburb_PostalCode 
	FOREIGN KEY (postcodeId) REFERENCES PostalCode (id)
GO





