--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.0.817
--  Created On : Tuesday, 02 October, 2007 
--  DBMS       : SQL Server 2000 
--  -------------------------------------------------- 

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('CachedMemberData') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CachedMemberData
GO

CREATE TABLE CachedMemberData ( 
	memberId uniqueidentifier NOT NULL,
	contactCount int NOT NULL,
	currentJobs nvarchar(100) NULL,
	currentJobTitles nvarchar(100) NULL,    -- Note that this may be multiple concatenated job titles, so the type is not "JobTitle". 
	interests nvarchar(100) NULL
)
GO

ALTER TABLE CachedMemberData ADD CONSTRAINT PK_CachedMemberData 
	PRIMARY KEY CLUSTERED (memberId)
GO

ALTER TABLE CachedMemberData ADD CONSTRAINT FK_CachedMemberData_Member 
	FOREIGN KEY (memberId) REFERENCES Member (id)
GO




EXEC sp_addextendedproperty 'MS_Description', 'Note that this may be multiple concatenated job titles, so the type is not "JobTitle".', 'User', dbo, 'table', CachedMemberData, 'column', currentJobTitles
GO


