DROP TABLE linkme_owner.account_transaction_line_item
DROP TABLE linkme_owner.account_transaction
DROP TABLE linkme_owner.administrator_profile
DROP TABLE linkme_owner.credit_card_purchase_details
DROP TABLE linkme_owner.credit_card_surcharge
DROP TABLE linkme_owner.credit_purchase_details
DROP TABLE linkme_owner.db_version
DROP TABLE linkme_owner.disabled_user_profile_info
DROP TABLE linkme_owner.RecruiterToCandidateEmail
DROP TABLE linkme_owner.Email
DROP TABLE linkme_owner.email_purchase_details
DROP TABLE linkme_owner.email_verification
DROP TABLE linkme_owner.employer_purchases
DROP TABLE linkme_owner.employer_viewed_networkers
DROP TABLE linkme_owner.endorsement_relationship
DROP TABLE linkme_owner.endorsement
DROP TABLE linkme_owner.event
DROP TABLE linkme_owner.EventLogExtraData
DROP TABLE linkme_owner.event_log_profile
DROP TABLE linkme_owner.event_log
DROP TABLE linkme_owner.invoice_sequence
DROP TABLE linkme_owner.linkme_mail_queue
DROP TABLE linkme_owner.locality
DROP TABLE linkme_owner.mail_merge_content_item
DROP TABLE linkme_owner.mail_merge_task
DROP TABLE linkme_owner.networker_assessment
DROP TABLE linkme_owner.networker_invites
DROP TABLE linkme_owner.networker_jobs
DROP TABLE linkme_owner.networker_overlooked_result
DROP TABLE linkme_owner.networker_overlooked_search_criteria
DROP TABLE linkme_owner.networker_overlooked_summary
DROP TABLE linkme_owner.networker_promotion
DROP TABLE linkme_owner.networker_purchased_result
DROP TABLE linkme_owner.networker_resume_data
DROP TABLE linkme_owner.networker_statistics
DROP TABLE linkme_owner.networkNodes
DROP TABLE linkme_owner.order_invoice
DROP TABLE linkme_owner.resume_purchase_details
DROP TABLE linkme_owner.resume_queue
DROP TABLE linkme_owner.resume_request
DROP TABLE linkme_owner.resume_request_summary
DROP TABLE linkme_owner.search_criteria
DROP TABLE linkme_owner.search_log_criteria
DROP TABLE linkme_owner.search_log_result
DROP TABLE linkme_owner.search_result
DROP TABLE linkme_owner.search_log
DROP TABLE linkme_owner.searches
DROP TABLE linkme_owner.state_synonym
DROP TABLE linkme_owner.user_account
DROP TABLE linkme_owner.user_alert_parameters
DROP TABLE linkme_owner.user_alert_data
DROP TABLE linkme_owner.user_data
DROP TABLE linkme_owner.user_profile_contact
DROP TABLE linkme_owner.user_profile_ideal_job
DROP TABLE linkme_owner.user_profile_pending_invite
DROP TABLE linkme_owner.user_profile_promotions
DROP TABLE linkme_owner.employer_profile
DROP TABLE linkme_owner.networker_profile
DROP TABLE linkme_owner.user_profile
DROP TABLE linkme_owner.[File]

-- Boom!
GO
