#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Query.Reports.Roles.Candidates.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinkMe")]
	public partial class CandidatesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResumeEntity(ResumeEntity instance);
    partial void UpdateResumeEntity(ResumeEntity instance);
    partial void DeleteResumeEntity(ResumeEntity instance);
    partial void InsertCandidateResumeEntity(CandidateResumeEntity instance);
    partial void UpdateCandidateResumeEntity(CandidateResumeEntity instance);
    partial void DeleteCandidateResumeEntity(CandidateResumeEntity instance);
    partial void InsertMemberEntity(MemberEntity instance);
    partial void UpdateMemberEntity(MemberEntity instance);
    partial void DeleteMemberEntity(MemberEntity instance);
    partial void InsertRegisteredUserEntity(RegisteredUserEntity instance);
    partial void UpdateRegisteredUserEntity(RegisteredUserEntity instance);
    partial void DeleteRegisteredUserEntity(RegisteredUserEntity instance);
    partial void InsertCandidateEntity(CandidateEntity instance);
    partial void UpdateCandidateEntity(CandidateEntity instance);
    partial void DeleteCandidateEntity(CandidateEntity instance);
    partial void InsertResumeEventEntity(ResumeEventEntity instance);
    partial void UpdateResumeEventEntity(ResumeEventEntity instance);
    partial void DeleteResumeEventEntity(ResumeEventEntity instance);
    #endregion
		
		public CandidatesDataContext() : 
				base(global::LinkMe.Query.Reports.Properties.Settings.Default.LinkMeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CandidatesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidatesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidatesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidatesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		internal System.Data.Linq.Table<ResumeEntity> ResumeEntities
		{
			get
			{
				return this.GetTable<ResumeEntity>();
			}
		}
		
		internal System.Data.Linq.Table<CandidateResumeEntity> CandidateResumeEntities
		{
			get
			{
				return this.GetTable<CandidateResumeEntity>();
			}
		}
		
		internal System.Data.Linq.Table<MemberEntity> MemberEntities
		{
			get
			{
				return this.GetTable<MemberEntity>();
			}
		}
		
		internal System.Data.Linq.Table<RegisteredUserEntity> RegisteredUserEntities
		{
			get
			{
				return this.GetTable<RegisteredUserEntity>();
			}
		}
		
		internal System.Data.Linq.Table<CandidateEntity> CandidateEntities
		{
			get
			{
				return this.GetTable<CandidateEntity>();
			}
		}
		
		internal System.Data.Linq.Table<ResumeEventEntity> ResumeEventEntities
		{
			get
			{
				return this.GetTable<ResumeEventEntity>();
			}
		}
		
		internal System.Data.Linq.Table<SearchableMemberEntity> SearchableMemberEntities
		{
			get
			{
				return this.GetTable<SearchableMemberEntity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Resume")]
	internal partial class ResumeEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<System.DateTime> _lastEditedTime;
		
		private string _courses;
		
		private string _awards;
		
		private string _skills;
		
		private string _objective;
		
		private string _summary;
		
		private string _other;
		
		private string _citizenship;
		
		private string _affiliations;
		
		private string _professional;
		
		private string _interests;
		
		private string _referees;
		
		private int _isEmpty;
		
		private EntitySet<CandidateResumeEntity> _CandidateResumeEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnlastEditedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastEditedTimeChanged();
    partial void OncoursesChanging(string value);
    partial void OncoursesChanged();
    partial void OnawardsChanging(string value);
    partial void OnawardsChanged();
    partial void OnskillsChanging(string value);
    partial void OnskillsChanged();
    partial void OnobjectiveChanging(string value);
    partial void OnobjectiveChanged();
    partial void OnsummaryChanging(string value);
    partial void OnsummaryChanged();
    partial void OnotherChanging(string value);
    partial void OnotherChanged();
    partial void OncitizenshipChanging(string value);
    partial void OncitizenshipChanged();
    partial void OnaffiliationsChanging(string value);
    partial void OnaffiliationsChanged();
    partial void OnprofessionalChanging(string value);
    partial void OnprofessionalChanged();
    partial void OninterestsChanging(string value);
    partial void OninterestsChanged();
    partial void OnrefereesChanging(string value);
    partial void OnrefereesChanged();
    partial void OnisEmptyChanging(int value);
    partial void OnisEmptyChanged();
    #endregion
		
		public ResumeEntity()
		{
			this._CandidateResumeEntities = new EntitySet<CandidateResumeEntity>(new Action<CandidateResumeEntity>(this.attach_CandidateResumeEntities), new Action<CandidateResumeEntity>(this.detach_CandidateResumeEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastEditedTime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> lastEditedTime
		{
			get
			{
				return this._lastEditedTime;
			}
			set
			{
				if ((this._lastEditedTime != value))
				{
					this.OnlastEditedTimeChanging(value);
					this.SendPropertyChanging();
					this._lastEditedTime = value;
					this.SendPropertyChanged("lastEditedTime");
					this.OnlastEditedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courses", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string courses
		{
			get
			{
				return this._courses;
			}
			set
			{
				if ((this._courses != value))
				{
					this.OncoursesChanging(value);
					this.SendPropertyChanging();
					this._courses = value;
					this.SendPropertyChanged("courses");
					this.OncoursesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_awards", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string awards
		{
			get
			{
				return this._awards;
			}
			set
			{
				if ((this._awards != value))
				{
					this.OnawardsChanging(value);
					this.SendPropertyChanging();
					this._awards = value;
					this.SendPropertyChanged("awards");
					this.OnawardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skills", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string skills
		{
			get
			{
				return this._skills;
			}
			set
			{
				if ((this._skills != value))
				{
					this.OnskillsChanging(value);
					this.SendPropertyChanging();
					this._skills = value;
					this.SendPropertyChanged("skills");
					this.OnskillsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objective", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string objective
		{
			get
			{
				return this._objective;
			}
			set
			{
				if ((this._objective != value))
				{
					this.OnobjectiveChanging(value);
					this.SendPropertyChanging();
					this._objective = value;
					this.SendPropertyChanged("objective");
					this.OnobjectiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_summary", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string summary
		{
			get
			{
				return this._summary;
			}
			set
			{
				if ((this._summary != value))
				{
					this.OnsummaryChanging(value);
					this.SendPropertyChanging();
					this._summary = value;
					this.SendPropertyChanged("summary");
					this.OnsummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string other
		{
			get
			{
				return this._other;
			}
			set
			{
				if ((this._other != value))
				{
					this.OnotherChanging(value);
					this.SendPropertyChanging();
					this._other = value;
					this.SendPropertyChanged("other");
					this.OnotherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_citizenship", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string citizenship
		{
			get
			{
				return this._citizenship;
			}
			set
			{
				if ((this._citizenship != value))
				{
					this.OncitizenshipChanging(value);
					this.SendPropertyChanging();
					this._citizenship = value;
					this.SendPropertyChanged("citizenship");
					this.OncitizenshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_affiliations", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string affiliations
		{
			get
			{
				return this._affiliations;
			}
			set
			{
				if ((this._affiliations != value))
				{
					this.OnaffiliationsChanging(value);
					this.SendPropertyChanging();
					this._affiliations = value;
					this.SendPropertyChanged("affiliations");
					this.OnaffiliationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_professional", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string professional
		{
			get
			{
				return this._professional;
			}
			set
			{
				if ((this._professional != value))
				{
					this.OnprofessionalChanging(value);
					this.SendPropertyChanging();
					this._professional = value;
					this.SendPropertyChanged("professional");
					this.OnprofessionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_interests", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string interests
		{
			get
			{
				return this._interests;
			}
			set
			{
				if ((this._interests != value))
				{
					this.OninterestsChanging(value);
					this.SendPropertyChanging();
					this._interests = value;
					this.SendPropertyChanged("interests");
					this.OninterestsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referees", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string referees
		{
			get
			{
				return this._referees;
			}
			set
			{
				if ((this._referees != value))
				{
					this.OnrefereesChanging(value);
					this.SendPropertyChanging();
					this._referees = value;
					this.SendPropertyChanged("referees");
					this.OnrefereesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEmpty", AutoSync=AutoSync.Always, DbType="Int NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int isEmpty
		{
			get
			{
				return this._isEmpty;
			}
			set
			{
				if ((this._isEmpty != value))
				{
					this.OnisEmptyChanging(value);
					this.SendPropertyChanging();
					this._isEmpty = value;
					this.SendPropertyChanged("isEmpty");
					this.OnisEmptyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeEntity_CandidateResumeEntity", Storage="_CandidateResumeEntities", ThisKey="id", OtherKey="resumeId")]
		public EntitySet<CandidateResumeEntity> CandidateResumeEntities
		{
			get
			{
				return this._CandidateResumeEntities;
			}
			set
			{
				this._CandidateResumeEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CandidateResumeEntities(CandidateResumeEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeEntity = this;
		}
		
		private void detach_CandidateResumeEntities(CandidateResumeEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CandidateResume")]
	internal partial class CandidateResumeEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _candidateId;
		
		private System.Guid _resumeId;
		
		private System.Nullable<System.Guid> _parsedFromFileId;
		
		private EntityRef<ResumeEntity> _ResumeEntity;
		
		private EntityRef<CandidateEntity> _CandidateEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncandidateIdChanging(System.Guid value);
    partial void OncandidateIdChanged();
    partial void OnresumeIdChanging(System.Guid value);
    partial void OnresumeIdChanged();
    partial void OnparsedFromFileIdChanging(System.Nullable<System.Guid> value);
    partial void OnparsedFromFileIdChanged();
    #endregion
		
		public CandidateResumeEntity()
		{
			this._ResumeEntity = default(EntityRef<ResumeEntity>);
			this._CandidateEntity = default(EntityRef<CandidateEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_candidateId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid candidateId
		{
			get
			{
				return this._candidateId;
			}
			set
			{
				if ((this._candidateId != value))
				{
					if (this._CandidateEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncandidateIdChanging(value);
					this.SendPropertyChanging();
					this._candidateId = value;
					this.SendPropertyChanged("candidateId");
					this.OncandidateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid resumeId
		{
			get
			{
				return this._resumeId;
			}
			set
			{
				if ((this._resumeId != value))
				{
					if (this._ResumeEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnresumeIdChanging(value);
					this.SendPropertyChanging();
					this._resumeId = value;
					this.SendPropertyChanged("resumeId");
					this.OnresumeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parsedFromFileId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> parsedFromFileId
		{
			get
			{
				return this._parsedFromFileId;
			}
			set
			{
				if ((this._parsedFromFileId != value))
				{
					this.OnparsedFromFileIdChanging(value);
					this.SendPropertyChanging();
					this._parsedFromFileId = value;
					this.SendPropertyChanged("parsedFromFileId");
					this.OnparsedFromFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeEntity_CandidateResumeEntity", Storage="_ResumeEntity", ThisKey="resumeId", OtherKey="id", IsForeignKey=true)]
		public ResumeEntity ResumeEntity
		{
			get
			{
				return this._ResumeEntity.Entity;
			}
			set
			{
				ResumeEntity previousValue = this._ResumeEntity.Entity;
				if (((previousValue != value) 
							|| (this._ResumeEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResumeEntity.Entity = null;
						previousValue.CandidateResumeEntities.Remove(this);
					}
					this._ResumeEntity.Entity = value;
					if ((value != null))
					{
						value.CandidateResumeEntities.Add(this);
						this._resumeId = value.id;
					}
					else
					{
						this._resumeId = default(System.Guid);
					}
					this.SendPropertyChanged("ResumeEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CandidateEntity_CandidateResumeEntity", Storage="_CandidateEntity", ThisKey="candidateId", OtherKey="id", IsForeignKey=true)]
		public CandidateEntity CandidateEntity
		{
			get
			{
				return this._CandidateEntity.Entity;
			}
			set
			{
				CandidateEntity previousValue = this._CandidateEntity.Entity;
				if (((previousValue != value) 
							|| (this._CandidateEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CandidateEntity.Entity = null;
						previousValue.CandidateResumeEntities.Remove(this);
					}
					this._CandidateEntity.Entity = value;
					if ((value != null))
					{
						value.CandidateResumeEntities.Add(this);
						this._candidateId = value.id;
					}
					else
					{
						this._candidateId = default(System.Guid);
					}
					this.SendPropertyChanged("CandidateEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Member")]
	internal partial class MemberEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<System.DateTime> _dateOfBirth;
		
		private byte _gender;
		
		private byte _employerAccess;
		
		private int _firstDegreeAccess;
		
		private int _secondDegreeAccess;
		
		private int _publicAccess;
		
		private System.Nullable<byte> _enteredReferralSourceId;
		
		private System.Guid _addressId;
		
		private System.Nullable<System.Guid> _profilePhotoId;
		
		private System.Nullable<int> _ethnicFlags;
		
		private System.Nullable<int> _disabilityFlags;
		
		private System.Nullable<byte> _dateOfBirthParts;
		
		private string _primaryPhoneNumber;
		
		private System.Nullable<byte> _primaryPhoneNumberType;
		
		private string _secondaryPhoneNumber;
		
		private System.Nullable<byte> _secondaryPhoneNumberType;
		
		private string _tertiaryPhoneNumber;
		
		private System.Nullable<byte> _tertiaryPhoneNumberType;
		
		private EntityRef<RegisteredUserEntity> _RegisteredUserEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OndateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfBirthChanged();
    partial void OngenderChanging(byte value);
    partial void OngenderChanged();
    partial void OnemployerAccessChanging(byte value);
    partial void OnemployerAccessChanged();
    partial void OnfirstDegreeAccessChanging(int value);
    partial void OnfirstDegreeAccessChanged();
    partial void OnsecondDegreeAccessChanging(int value);
    partial void OnsecondDegreeAccessChanged();
    partial void OnpublicAccessChanging(int value);
    partial void OnpublicAccessChanged();
    partial void OnenteredReferralSourceIdChanging(System.Nullable<byte> value);
    partial void OnenteredReferralSourceIdChanged();
    partial void OnaddressIdChanging(System.Guid value);
    partial void OnaddressIdChanged();
    partial void OnprofilePhotoIdChanging(System.Nullable<System.Guid> value);
    partial void OnprofilePhotoIdChanged();
    partial void OnethnicFlagsChanging(System.Nullable<int> value);
    partial void OnethnicFlagsChanged();
    partial void OndisabilityFlagsChanging(System.Nullable<int> value);
    partial void OndisabilityFlagsChanged();
    partial void OndateOfBirthPartsChanging(System.Nullable<byte> value);
    partial void OndateOfBirthPartsChanged();
    partial void OnprimaryPhoneNumberChanging(string value);
    partial void OnprimaryPhoneNumberChanged();
    partial void OnprimaryPhoneNumberTypeChanging(System.Nullable<byte> value);
    partial void OnprimaryPhoneNumberTypeChanged();
    partial void OnsecondaryPhoneNumberChanging(string value);
    partial void OnsecondaryPhoneNumberChanged();
    partial void OnsecondaryPhoneNumberTypeChanging(System.Nullable<byte> value);
    partial void OnsecondaryPhoneNumberTypeChanged();
    partial void OntertiaryPhoneNumberChanging(string value);
    partial void OntertiaryPhoneNumberChanged();
    partial void OntertiaryPhoneNumberTypeChanging(System.Nullable<byte> value);
    partial void OntertiaryPhoneNumberTypeChanged();
    #endregion
		
		public MemberEntity()
		{
			this._RegisteredUserEntity = default(EntityRef<RegisteredUserEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._RegisteredUserEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfBirth", DbType="SmallDateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> dateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				if ((this._dateOfBirth != value))
				{
					this.OndateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._dateOfBirth = value;
					this.SendPropertyChanged("dateOfBirth");
					this.OndateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employerAccess", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte employerAccess
		{
			get
			{
				return this._employerAccess;
			}
			set
			{
				if ((this._employerAccess != value))
				{
					this.OnemployerAccessChanging(value);
					this.SendPropertyChanging();
					this._employerAccess = value;
					this.SendPropertyChanged("employerAccess");
					this.OnemployerAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstDegreeAccess", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int firstDegreeAccess
		{
			get
			{
				return this._firstDegreeAccess;
			}
			set
			{
				if ((this._firstDegreeAccess != value))
				{
					this.OnfirstDegreeAccessChanging(value);
					this.SendPropertyChanging();
					this._firstDegreeAccess = value;
					this.SendPropertyChanged("firstDegreeAccess");
					this.OnfirstDegreeAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondDegreeAccess", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int secondDegreeAccess
		{
			get
			{
				return this._secondDegreeAccess;
			}
			set
			{
				if ((this._secondDegreeAccess != value))
				{
					this.OnsecondDegreeAccessChanging(value);
					this.SendPropertyChanging();
					this._secondDegreeAccess = value;
					this.SendPropertyChanged("secondDegreeAccess");
					this.OnsecondDegreeAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publicAccess", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int publicAccess
		{
			get
			{
				return this._publicAccess;
			}
			set
			{
				if ((this._publicAccess != value))
				{
					this.OnpublicAccessChanging(value);
					this.SendPropertyChanging();
					this._publicAccess = value;
					this.SendPropertyChanged("publicAccess");
					this.OnpublicAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enteredReferralSourceId", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> enteredReferralSourceId
		{
			get
			{
				return this._enteredReferralSourceId;
			}
			set
			{
				if ((this._enteredReferralSourceId != value))
				{
					this.OnenteredReferralSourceIdChanging(value);
					this.SendPropertyChanging();
					this._enteredReferralSourceId = value;
					this.SendPropertyChanged("enteredReferralSourceId");
					this.OnenteredReferralSourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid addressId
		{
			get
			{
				return this._addressId;
			}
			set
			{
				if ((this._addressId != value))
				{
					this.OnaddressIdChanging(value);
					this.SendPropertyChanging();
					this._addressId = value;
					this.SendPropertyChanged("addressId");
					this.OnaddressIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profilePhotoId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> profilePhotoId
		{
			get
			{
				return this._profilePhotoId;
			}
			set
			{
				if ((this._profilePhotoId != value))
				{
					this.OnprofilePhotoIdChanging(value);
					this.SendPropertyChanging();
					this._profilePhotoId = value;
					this.SendPropertyChanged("profilePhotoId");
					this.OnprofilePhotoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ethnicFlags", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ethnicFlags
		{
			get
			{
				return this._ethnicFlags;
			}
			set
			{
				if ((this._ethnicFlags != value))
				{
					this.OnethnicFlagsChanging(value);
					this.SendPropertyChanging();
					this._ethnicFlags = value;
					this.SendPropertyChanged("ethnicFlags");
					this.OnethnicFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disabilityFlags", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> disabilityFlags
		{
			get
			{
				return this._disabilityFlags;
			}
			set
			{
				if ((this._disabilityFlags != value))
				{
					this.OndisabilityFlagsChanging(value);
					this.SendPropertyChanging();
					this._disabilityFlags = value;
					this.SendPropertyChanged("disabilityFlags");
					this.OndisabilityFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfBirthParts", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> dateOfBirthParts
		{
			get
			{
				return this._dateOfBirthParts;
			}
			set
			{
				if ((this._dateOfBirthParts != value))
				{
					this.OndateOfBirthPartsChanging(value);
					this.SendPropertyChanging();
					this._dateOfBirthParts = value;
					this.SendPropertyChanged("dateOfBirthParts");
					this.OndateOfBirthPartsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primaryPhoneNumber", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string primaryPhoneNumber
		{
			get
			{
				return this._primaryPhoneNumber;
			}
			set
			{
				if ((this._primaryPhoneNumber != value))
				{
					this.OnprimaryPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._primaryPhoneNumber = value;
					this.SendPropertyChanged("primaryPhoneNumber");
					this.OnprimaryPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primaryPhoneNumberType", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> primaryPhoneNumberType
		{
			get
			{
				return this._primaryPhoneNumberType;
			}
			set
			{
				if ((this._primaryPhoneNumberType != value))
				{
					this.OnprimaryPhoneNumberTypeChanging(value);
					this.SendPropertyChanging();
					this._primaryPhoneNumberType = value;
					this.SendPropertyChanged("primaryPhoneNumberType");
					this.OnprimaryPhoneNumberTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondaryPhoneNumber", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string secondaryPhoneNumber
		{
			get
			{
				return this._secondaryPhoneNumber;
			}
			set
			{
				if ((this._secondaryPhoneNumber != value))
				{
					this.OnsecondaryPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._secondaryPhoneNumber = value;
					this.SendPropertyChanged("secondaryPhoneNumber");
					this.OnsecondaryPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondaryPhoneNumberType", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> secondaryPhoneNumberType
		{
			get
			{
				return this._secondaryPhoneNumberType;
			}
			set
			{
				if ((this._secondaryPhoneNumberType != value))
				{
					this.OnsecondaryPhoneNumberTypeChanging(value);
					this.SendPropertyChanging();
					this._secondaryPhoneNumberType = value;
					this.SendPropertyChanged("secondaryPhoneNumberType");
					this.OnsecondaryPhoneNumberTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tertiaryPhoneNumber", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string tertiaryPhoneNumber
		{
			get
			{
				return this._tertiaryPhoneNumber;
			}
			set
			{
				if ((this._tertiaryPhoneNumber != value))
				{
					this.OntertiaryPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._tertiaryPhoneNumber = value;
					this.SendPropertyChanged("tertiaryPhoneNumber");
					this.OntertiaryPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tertiaryPhoneNumberType", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> tertiaryPhoneNumberType
		{
			get
			{
				return this._tertiaryPhoneNumberType;
			}
			set
			{
				if ((this._tertiaryPhoneNumberType != value))
				{
					this.OntertiaryPhoneNumberTypeChanging(value);
					this.SendPropertyChanging();
					this._tertiaryPhoneNumberType = value;
					this.SendPropertyChanged("tertiaryPhoneNumberType");
					this.OntertiaryPhoneNumberTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegisteredUserEntity_MemberEntity", Storage="_RegisteredUserEntity", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public RegisteredUserEntity RegisteredUserEntity
		{
			get
			{
				return this._RegisteredUserEntity.Entity;
			}
			set
			{
				RegisteredUserEntity previousValue = this._RegisteredUserEntity.Entity;
				if (((previousValue != value) 
							|| (this._RegisteredUserEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RegisteredUserEntity.Entity = null;
						previousValue.MemberEntity = null;
					}
					this._RegisteredUserEntity.Entity = value;
					if ((value != null))
					{
						value.MemberEntity = this;
						this._id = value.id;
					}
					else
					{
						this._id = default(System.Guid);
					}
					this.SendPropertyChanged("RegisteredUserEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegisteredUser")]
	internal partial class RegisteredUserEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _loginId;
		
		private System.DateTime _createdTime;
		
		private string _emailAddress;
		
		private string _firstName;
		
		private string _lastName;
		
		private short _flags;
		
		private string _passwordHash;
		
		private bool _emailAddressVerified;
		
		private string _secondaryEmailAddress;
		
		private System.Nullable<bool> _secondaryEmailAddressVerified;
		
		private EntityRef<MemberEntity> _MemberEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnloginIdChanging(string value);
    partial void OnloginIdChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    partial void OnemailAddressChanging(string value);
    partial void OnemailAddressChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnflagsChanging(short value);
    partial void OnflagsChanged();
    partial void OnpasswordHashChanging(string value);
    partial void OnpasswordHashChanged();
    partial void OnemailAddressVerifiedChanging(bool value);
    partial void OnemailAddressVerifiedChanged();
    partial void OnsecondaryEmailAddressChanging(string value);
    partial void OnsecondaryEmailAddressChanged();
    partial void OnsecondaryEmailAddressVerifiedChanging(System.Nullable<bool> value);
    partial void OnsecondaryEmailAddressVerifiedChanged();
    #endregion
		
		public RegisteredUserEntity()
		{
			this._MemberEntity = default(EntityRef<MemberEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loginId", DbType="NVarChar(320)", UpdateCheck=UpdateCheck.Never)]
		public string loginId
		{
			get
			{
				return this._loginId;
			}
			set
			{
				if ((this._loginId != value))
				{
					this.OnloginIdChanging(value);
					this.SendPropertyChanging();
					this._loginId = value;
					this.SendPropertyChanged("loginId");
					this.OnloginIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAddress", DbType="NVarChar(320) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string emailAddress
		{
			get
			{
				return this._emailAddress;
			}
			set
			{
				if ((this._emailAddress != value))
				{
					this.OnemailAddressChanging(value);
					this.SendPropertyChanging();
					this._emailAddress = value;
					this.SendPropertyChanged("emailAddress");
					this.OnemailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(30) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flags", DbType="SmallInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public short flags
		{
			get
			{
				return this._flags;
			}
			set
			{
				if ((this._flags != value))
				{
					this.OnflagsChanging(value);
					this.SendPropertyChanging();
					this._flags = value;
					this.SendPropertyChanged("flags");
					this.OnflagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passwordHash", DbType="Char(24)", UpdateCheck=UpdateCheck.Never)]
		public string passwordHash
		{
			get
			{
				return this._passwordHash;
			}
			set
			{
				if ((this._passwordHash != value))
				{
					this.OnpasswordHashChanging(value);
					this.SendPropertyChanging();
					this._passwordHash = value;
					this.SendPropertyChanged("passwordHash");
					this.OnpasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAddressVerified", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool emailAddressVerified
		{
			get
			{
				return this._emailAddressVerified;
			}
			set
			{
				if ((this._emailAddressVerified != value))
				{
					this.OnemailAddressVerifiedChanging(value);
					this.SendPropertyChanging();
					this._emailAddressVerified = value;
					this.SendPropertyChanged("emailAddressVerified");
					this.OnemailAddressVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondaryEmailAddress", DbType="NVarChar(320)", UpdateCheck=UpdateCheck.Never)]
		public string secondaryEmailAddress
		{
			get
			{
				return this._secondaryEmailAddress;
			}
			set
			{
				if ((this._secondaryEmailAddress != value))
				{
					this.OnsecondaryEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._secondaryEmailAddress = value;
					this.SendPropertyChanged("secondaryEmailAddress");
					this.OnsecondaryEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_secondaryEmailAddressVerified", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> secondaryEmailAddressVerified
		{
			get
			{
				return this._secondaryEmailAddressVerified;
			}
			set
			{
				if ((this._secondaryEmailAddressVerified != value))
				{
					this.OnsecondaryEmailAddressVerifiedChanging(value);
					this.SendPropertyChanging();
					this._secondaryEmailAddressVerified = value;
					this.SendPropertyChanged("secondaryEmailAddressVerified");
					this.OnsecondaryEmailAddressVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RegisteredUserEntity_MemberEntity", Storage="_MemberEntity", ThisKey="id", OtherKey="id", IsUnique=true, IsForeignKey=false)]
		public MemberEntity MemberEntity
		{
			get
			{
				return this._MemberEntity.Entity;
			}
			set
			{
				MemberEntity previousValue = this._MemberEntity.Entity;
				if (((previousValue != value) 
							|| (this._MemberEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MemberEntity.Entity = null;
						previousValue.RegisteredUserEntity = null;
					}
					this._MemberEntity.Entity = value;
					if ((value != null))
					{
						value.RegisteredUserEntity = this;
					}
					this.SendPropertyChanged("MemberEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Candidate")]
	internal partial class CandidateEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private byte _status;
		
		private string _desiredJobTitle;
		
		private byte _desiredJobTypes;
		
		private System.Nullable<decimal> _desiredSalaryLower;
		
		private System.Nullable<decimal> _desiredSalaryUpper;
		
		private byte _desiredSalaryRateType;
		
		private byte _relocationPreference;
		
		private System.Nullable<System.Guid> _diaryId;
		
		private System.Nullable<byte> _highestEducationLevel;
		
		private System.Nullable<byte> _recentSeniority;
		
		private System.Nullable<byte> _recentProfession;
		
		private System.Nullable<byte> _visaStatus;
		
		private System.Nullable<System.DateTime> _lastEditedTime;
		
		private EntitySet<CandidateResumeEntity> _CandidateResumeEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    partial void OndesiredJobTitleChanging(string value);
    partial void OndesiredJobTitleChanged();
    partial void OndesiredJobTypesChanging(byte value);
    partial void OndesiredJobTypesChanged();
    partial void OndesiredSalaryLowerChanging(System.Nullable<decimal> value);
    partial void OndesiredSalaryLowerChanged();
    partial void OndesiredSalaryUpperChanging(System.Nullable<decimal> value);
    partial void OndesiredSalaryUpperChanged();
    partial void OndesiredSalaryRateTypeChanging(byte value);
    partial void OndesiredSalaryRateTypeChanged();
    partial void OnrelocationPreferenceChanging(byte value);
    partial void OnrelocationPreferenceChanged();
    partial void OndiaryIdChanging(System.Nullable<System.Guid> value);
    partial void OndiaryIdChanged();
    partial void OnhighestEducationLevelChanging(System.Nullable<byte> value);
    partial void OnhighestEducationLevelChanged();
    partial void OnrecentSeniorityChanging(System.Nullable<byte> value);
    partial void OnrecentSeniorityChanged();
    partial void OnrecentProfessionChanging(System.Nullable<byte> value);
    partial void OnrecentProfessionChanged();
    partial void OnvisaStatusChanging(System.Nullable<byte> value);
    partial void OnvisaStatusChanged();
    partial void OnlastEditedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastEditedTimeChanged();
    #endregion
		
		public CandidateEntity()
		{
			this._CandidateResumeEntities = new EntitySet<CandidateResumeEntity>(new Action<CandidateResumeEntity>(this.attach_CandidateResumeEntities), new Action<CandidateResumeEntity>(this.detach_CandidateResumeEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desiredJobTitle", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string desiredJobTitle
		{
			get
			{
				return this._desiredJobTitle;
			}
			set
			{
				if ((this._desiredJobTitle != value))
				{
					this.OndesiredJobTitleChanging(value);
					this.SendPropertyChanging();
					this._desiredJobTitle = value;
					this.SendPropertyChanged("desiredJobTitle");
					this.OndesiredJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desiredJobTypes", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte desiredJobTypes
		{
			get
			{
				return this._desiredJobTypes;
			}
			set
			{
				if ((this._desiredJobTypes != value))
				{
					this.OndesiredJobTypesChanging(value);
					this.SendPropertyChanging();
					this._desiredJobTypes = value;
					this.SendPropertyChanged("desiredJobTypes");
					this.OndesiredJobTypesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desiredSalaryLower", DbType="Decimal(18,8)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> desiredSalaryLower
		{
			get
			{
				return this._desiredSalaryLower;
			}
			set
			{
				if ((this._desiredSalaryLower != value))
				{
					this.OndesiredSalaryLowerChanging(value);
					this.SendPropertyChanging();
					this._desiredSalaryLower = value;
					this.SendPropertyChanged("desiredSalaryLower");
					this.OndesiredSalaryLowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desiredSalaryUpper", DbType="Decimal(18,8)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> desiredSalaryUpper
		{
			get
			{
				return this._desiredSalaryUpper;
			}
			set
			{
				if ((this._desiredSalaryUpper != value))
				{
					this.OndesiredSalaryUpperChanging(value);
					this.SendPropertyChanging();
					this._desiredSalaryUpper = value;
					this.SendPropertyChanged("desiredSalaryUpper");
					this.OndesiredSalaryUpperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desiredSalaryRateType", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte desiredSalaryRateType
		{
			get
			{
				return this._desiredSalaryRateType;
			}
			set
			{
				if ((this._desiredSalaryRateType != value))
				{
					this.OndesiredSalaryRateTypeChanging(value);
					this.SendPropertyChanging();
					this._desiredSalaryRateType = value;
					this.SendPropertyChanged("desiredSalaryRateType");
					this.OndesiredSalaryRateTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relocationPreference", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte relocationPreference
		{
			get
			{
				return this._relocationPreference;
			}
			set
			{
				if ((this._relocationPreference != value))
				{
					this.OnrelocationPreferenceChanging(value);
					this.SendPropertyChanging();
					this._relocationPreference = value;
					this.SendPropertyChanged("relocationPreference");
					this.OnrelocationPreferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaryId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> diaryId
		{
			get
			{
				return this._diaryId;
			}
			set
			{
				if ((this._diaryId != value))
				{
					this.OndiaryIdChanging(value);
					this.SendPropertyChanging();
					this._diaryId = value;
					this.SendPropertyChanged("diaryId");
					this.OndiaryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_highestEducationLevel", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> highestEducationLevel
		{
			get
			{
				return this._highestEducationLevel;
			}
			set
			{
				if ((this._highestEducationLevel != value))
				{
					this.OnhighestEducationLevelChanging(value);
					this.SendPropertyChanging();
					this._highestEducationLevel = value;
					this.SendPropertyChanged("highestEducationLevel");
					this.OnhighestEducationLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recentSeniority", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> recentSeniority
		{
			get
			{
				return this._recentSeniority;
			}
			set
			{
				if ((this._recentSeniority != value))
				{
					this.OnrecentSeniorityChanging(value);
					this.SendPropertyChanging();
					this._recentSeniority = value;
					this.SendPropertyChanged("recentSeniority");
					this.OnrecentSeniorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recentProfession", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> recentProfession
		{
			get
			{
				return this._recentProfession;
			}
			set
			{
				if ((this._recentProfession != value))
				{
					this.OnrecentProfessionChanging(value);
					this.SendPropertyChanging();
					this._recentProfession = value;
					this.SendPropertyChanged("recentProfession");
					this.OnrecentProfessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visaStatus", DbType="TinyInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<byte> visaStatus
		{
			get
			{
				return this._visaStatus;
			}
			set
			{
				if ((this._visaStatus != value))
				{
					this.OnvisaStatusChanging(value);
					this.SendPropertyChanging();
					this._visaStatus = value;
					this.SendPropertyChanged("visaStatus");
					this.OnvisaStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastEditedTime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> lastEditedTime
		{
			get
			{
				return this._lastEditedTime;
			}
			set
			{
				if ((this._lastEditedTime != value))
				{
					this.OnlastEditedTimeChanging(value);
					this.SendPropertyChanging();
					this._lastEditedTime = value;
					this.SendPropertyChanged("lastEditedTime");
					this.OnlastEditedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CandidateEntity_CandidateResumeEntity", Storage="_CandidateResumeEntities", ThisKey="id", OtherKey="candidateId")]
		public EntitySet<CandidateResumeEntity> CandidateResumeEntities
		{
			get
			{
				return this._CandidateResumeEntities;
			}
			set
			{
				this._CandidateResumeEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CandidateResumeEntities(CandidateResumeEntity entity)
		{
			this.SendPropertyChanging();
			entity.CandidateEntity = this;
		}
		
		private void detach_CandidateResumeEntities(CandidateResumeEntity entity)
		{
			this.SendPropertyChanging();
			entity.CandidateEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResumeEvent")]
	internal partial class ResumeEventEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.DateTime _time;
		
		private int _eventType;
		
		private System.Guid _candidateId;
		
		private System.Guid _resumeId;
		
		private bool _resumeCreated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OntimeChanging(System.DateTime value);
    partial void OntimeChanged();
    partial void OneventTypeChanging(int value);
    partial void OneventTypeChanged();
    partial void OncandidateIdChanging(System.Guid value);
    partial void OncandidateIdChanged();
    partial void OnresumeIdChanging(System.Guid value);
    partial void OnresumeIdChanged();
    partial void OnresumeCreatedChanging(bool value);
    partial void OnresumeCreatedChanged();
    #endregion
		
		public ResumeEventEntity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventType", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int eventType
		{
			get
			{
				return this._eventType;
			}
			set
			{
				if ((this._eventType != value))
				{
					this.OneventTypeChanging(value);
					this.SendPropertyChanging();
					this._eventType = value;
					this.SendPropertyChanged("eventType");
					this.OneventTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_candidateId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid candidateId
		{
			get
			{
				return this._candidateId;
			}
			set
			{
				if ((this._candidateId != value))
				{
					this.OncandidateIdChanging(value);
					this.SendPropertyChanging();
					this._candidateId = value;
					this.SendPropertyChanged("candidateId");
					this.OncandidateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid resumeId
		{
			get
			{
				return this._resumeId;
			}
			set
			{
				if ((this._resumeId != value))
				{
					this.OnresumeIdChanging(value);
					this.SendPropertyChanging();
					this._resumeId = value;
					this.SendPropertyChanged("resumeId");
					this.OnresumeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeCreated", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool resumeCreated
		{
			get
			{
				return this._resumeCreated;
			}
			set
			{
				if ((this._resumeCreated != value))
				{
					this.OnresumeCreatedChanging(value);
					this.SendPropertyChanging();
					this._resumeCreated = value;
					this.SendPropertyChanged("resumeCreated");
					this.OnresumeCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SearchableMember")]
	internal partial class SearchableMemberEntity
	{
		
		private System.Guid _id;
		
		public SearchableMemberEntity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
