#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Query.Search.Test.Members.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinkMe")]
	public partial class MembersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResumeSearchCriteriaEntity(ResumeSearchCriteriaEntity instance);
    partial void UpdateResumeSearchCriteriaEntity(ResumeSearchCriteriaEntity instance);
    partial void DeleteResumeSearchCriteriaEntity(ResumeSearchCriteriaEntity instance);
    partial void InsertResumeSearchCriteriaSetEntity(ResumeSearchCriteriaSetEntity instance);
    partial void UpdateResumeSearchCriteriaSetEntity(ResumeSearchCriteriaSetEntity instance);
    partial void DeleteResumeSearchCriteriaSetEntity(ResumeSearchCriteriaSetEntity instance);
    partial void InsertResumeSearchResultEntity(ResumeSearchResultEntity instance);
    partial void UpdateResumeSearchResultEntity(ResumeSearchResultEntity instance);
    partial void DeleteResumeSearchResultEntity(ResumeSearchResultEntity instance);
    partial void InsertResumeSearchResultSetEntity(ResumeSearchResultSetEntity instance);
    partial void UpdateResumeSearchResultSetEntity(ResumeSearchResultSetEntity instance);
    partial void DeleteResumeSearchResultSetEntity(ResumeSearchResultSetEntity instance);
    partial void InsertSavedResumeSearchEntity(SavedResumeSearchEntity instance);
    partial void UpdateSavedResumeSearchEntity(SavedResumeSearchEntity instance);
    partial void DeleteSavedResumeSearchEntity(SavedResumeSearchEntity instance);
    partial void InsertResumeSearchEntity(ResumeSearchEntity instance);
    partial void UpdateResumeSearchEntity(ResumeSearchEntity instance);
    partial void DeleteResumeSearchEntity(ResumeSearchEntity instance);
    #endregion
		
		public MembersDataContext() : 
				base(global::LinkMe.Query.Search.Test.Properties.Settings.Default.LinkMeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MembersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MembersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MembersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MembersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		internal System.Data.Linq.Table<ResumeSearchCriteriaEntity> ResumeSearchCriteriaEntities
		{
			get
			{
				return this.GetTable<ResumeSearchCriteriaEntity>();
			}
		}
		
		internal System.Data.Linq.Table<ResumeSearchCriteriaSetEntity> ResumeSearchCriteriaSetEntities
		{
			get
			{
				return this.GetTable<ResumeSearchCriteriaSetEntity>();
			}
		}
		
		internal System.Data.Linq.Table<ResumeSearchResultEntity> ResumeSearchResultEntities
		{
			get
			{
				return this.GetTable<ResumeSearchResultEntity>();
			}
		}
		
		internal System.Data.Linq.Table<ResumeSearchResultSetEntity> ResumeSearchResultSetEntities
		{
			get
			{
				return this.GetTable<ResumeSearchResultSetEntity>();
			}
		}
		
		internal System.Data.Linq.Table<SavedResumeSearchEntity> SavedResumeSearchEntities
		{
			get
			{
				return this.GetTable<SavedResumeSearchEntity>();
			}
		}
		
		internal System.Data.Linq.Table<ResumeSearchEntity> ResumeSearchEntities
		{
			get
			{
				return this.GetTable<ResumeSearchEntity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResumeSearchCriteria")]
	internal partial class ResumeSearchCriteriaEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _setId;
		
		private string _name;
		
		private string _value;
		
		private EntityRef<ResumeSearchCriteriaSetEntity> _ResumeSearchCriteriaSetEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsetIdChanging(System.Guid value);
    partial void OnsetIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    #endregion
		
		public ResumeSearchCriteriaEntity()
		{
			this._ResumeSearchCriteriaSetEntity = default(EntityRef<ResumeSearchCriteriaSetEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid setId
		{
			get
			{
				return this._setId;
			}
			set
			{
				if ((this._setId != value))
				{
					if (this._ResumeSearchCriteriaSetEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsetIdChanging(value);
					this.SendPropertyChanging();
					this._setId = value;
					this.SendPropertyChanged("setId");
					this.OnsetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(19) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchCriteriaSetEntity_ResumeSearchCriteriaEntity", Storage="_ResumeSearchCriteriaSetEntity", ThisKey="setId", OtherKey="id", IsForeignKey=true)]
		public ResumeSearchCriteriaSetEntity ResumeSearchCriteriaSetEntity
		{
			get
			{
				return this._ResumeSearchCriteriaSetEntity.Entity;
			}
			set
			{
				ResumeSearchCriteriaSetEntity previousValue = this._ResumeSearchCriteriaSetEntity.Entity;
				if (((previousValue != value) 
							|| (this._ResumeSearchCriteriaSetEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResumeSearchCriteriaSetEntity.Entity = null;
						previousValue.ResumeSearchCriteriaEntities.Remove(this);
					}
					this._ResumeSearchCriteriaSetEntity.Entity = value;
					if ((value != null))
					{
						value.ResumeSearchCriteriaEntities.Add(this);
						this._setId = value.id;
					}
					else
					{
						this._setId = default(System.Guid);
					}
					this.SendPropertyChanged("ResumeSearchCriteriaSetEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResumeSearchCriteriaSet")]
	internal partial class ResumeSearchCriteriaSetEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _type;
		
		private EntitySet<ResumeSearchCriteriaEntity> _ResumeSearchCriteriaEntities;
		
		private EntitySet<SavedResumeSearchEntity> _SavedResumeSearchEntities;
		
		private EntitySet<ResumeSearchEntity> _ResumeSearchEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public ResumeSearchCriteriaSetEntity()
		{
			this._ResumeSearchCriteriaEntities = new EntitySet<ResumeSearchCriteriaEntity>(new Action<ResumeSearchCriteriaEntity>(this.attach_ResumeSearchCriteriaEntities), new Action<ResumeSearchCriteriaEntity>(this.detach_ResumeSearchCriteriaEntities));
			this._SavedResumeSearchEntities = new EntitySet<SavedResumeSearchEntity>(new Action<SavedResumeSearchEntity>(this.attach_SavedResumeSearchEntities), new Action<SavedResumeSearchEntity>(this.detach_SavedResumeSearchEntities));
			this._ResumeSearchEntities = new EntitySet<ResumeSearchEntity>(new Action<ResumeSearchEntity>(this.attach_ResumeSearchEntities), new Action<ResumeSearchEntity>(this.detach_ResumeSearchEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchCriteriaSetEntity_ResumeSearchCriteriaEntity", Storage="_ResumeSearchCriteriaEntities", ThisKey="id", OtherKey="setId")]
		public EntitySet<ResumeSearchCriteriaEntity> ResumeSearchCriteriaEntities
		{
			get
			{
				return this._ResumeSearchCriteriaEntities;
			}
			set
			{
				this._ResumeSearchCriteriaEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchCriteriaSetEntity_SavedResumeSearchEntity", Storage="_SavedResumeSearchEntities", ThisKey="id", OtherKey="criteriaSetId")]
		public EntitySet<SavedResumeSearchEntity> SavedResumeSearchEntities
		{
			get
			{
				return this._SavedResumeSearchEntities;
			}
			set
			{
				this._SavedResumeSearchEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchCriteriaSetEntity_ResumeSearchEntity", Storage="_ResumeSearchEntities", ThisKey="id", OtherKey="criteriaSetId")]
		public EntitySet<ResumeSearchEntity> ResumeSearchEntities
		{
			get
			{
				return this._ResumeSearchEntities;
			}
			set
			{
				this._ResumeSearchEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ResumeSearchCriteriaEntities(ResumeSearchCriteriaEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchCriteriaSetEntity = this;
		}
		
		private void detach_ResumeSearchCriteriaEntities(ResumeSearchCriteriaEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchCriteriaSetEntity = null;
		}
		
		private void attach_SavedResumeSearchEntities(SavedResumeSearchEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchCriteriaSetEntity = this;
		}
		
		private void detach_SavedResumeSearchEntities(SavedResumeSearchEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchCriteriaSetEntity = null;
		}
		
		private void attach_ResumeSearchEntities(ResumeSearchEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchCriteriaSetEntity = this;
		}
		
		private void detach_ResumeSearchEntities(ResumeSearchEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchCriteriaSetEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResumeSearchResult")]
	internal partial class ResumeSearchResultEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _setId;
		
		private short _rank;
		
		private System.Guid _resumeId;
		
		private EntityRef<ResumeSearchResultSetEntity> _ResumeSearchResultSetEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsetIdChanging(System.Guid value);
    partial void OnsetIdChanged();
    partial void OnrankChanging(short value);
    partial void OnrankChanged();
    partial void OnresumeIdChanging(System.Guid value);
    partial void OnresumeIdChanged();
    #endregion
		
		public ResumeSearchResultEntity()
		{
			this._ResumeSearchResultSetEntity = default(EntityRef<ResumeSearchResultSetEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid setId
		{
			get
			{
				return this._setId;
			}
			set
			{
				if ((this._setId != value))
				{
					if (this._ResumeSearchResultSetEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsetIdChanging(value);
					this.SendPropertyChanging();
					this._setId = value;
					this.SendPropertyChanged("setId");
					this.OnsetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rank", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				if ((this._rank != value))
				{
					this.OnrankChanging(value);
					this.SendPropertyChanging();
					this._rank = value;
					this.SendPropertyChanged("rank");
					this.OnrankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumeId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid resumeId
		{
			get
			{
				return this._resumeId;
			}
			set
			{
				if ((this._resumeId != value))
				{
					this.OnresumeIdChanging(value);
					this.SendPropertyChanging();
					this._resumeId = value;
					this.SendPropertyChanged("resumeId");
					this.OnresumeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchResultSetEntity_ResumeSearchResultEntity", Storage="_ResumeSearchResultSetEntity", ThisKey="setId", OtherKey="id", IsForeignKey=true)]
		public ResumeSearchResultSetEntity ResumeSearchResultSetEntity
		{
			get
			{
				return this._ResumeSearchResultSetEntity.Entity;
			}
			set
			{
				ResumeSearchResultSetEntity previousValue = this._ResumeSearchResultSetEntity.Entity;
				if (((previousValue != value) 
							|| (this._ResumeSearchResultSetEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResumeSearchResultSetEntity.Entity = null;
						previousValue.ResumeSearchResultEntities.Remove(this);
					}
					this._ResumeSearchResultSetEntity.Entity = value;
					if ((value != null))
					{
						value.ResumeSearchResultEntities.Add(this);
						this._setId = value.id;
					}
					else
					{
						this._setId = default(System.Guid);
					}
					this.SendPropertyChanged("ResumeSearchResultSetEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResumeSearchResultSet")]
	internal partial class ResumeSearchResultSetEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private int _count;
		
		private EntitySet<ResumeSearchResultEntity> _ResumeSearchResultEntities;
		
		private EntitySet<ResumeSearchEntity> _ResumeSearchEntities;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncountChanging(int value);
    partial void OncountChanged();
    #endregion
		
		public ResumeSearchResultSetEntity()
		{
			this._ResumeSearchResultEntities = new EntitySet<ResumeSearchResultEntity>(new Action<ResumeSearchResultEntity>(this.attach_ResumeSearchResultEntities), new Action<ResumeSearchResultEntity>(this.detach_ResumeSearchResultEntities));
			this._ResumeSearchEntities = new EntitySet<ResumeSearchEntity>(new Action<ResumeSearchEntity>(this.attach_ResumeSearchEntities), new Action<ResumeSearchEntity>(this.detach_ResumeSearchEntities));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int NOT NULL")]
		public int count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this.OncountChanging(value);
					this.SendPropertyChanging();
					this._count = value;
					this.SendPropertyChanged("count");
					this.OncountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchResultSetEntity_ResumeSearchResultEntity", Storage="_ResumeSearchResultEntities", ThisKey="id", OtherKey="setId")]
		public EntitySet<ResumeSearchResultEntity> ResumeSearchResultEntities
		{
			get
			{
				return this._ResumeSearchResultEntities;
			}
			set
			{
				this._ResumeSearchResultEntities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchResultSetEntity_ResumeSearchEntity", Storage="_ResumeSearchEntities", ThisKey="id", OtherKey="resultSetId")]
		public EntitySet<ResumeSearchEntity> ResumeSearchEntities
		{
			get
			{
				return this._ResumeSearchEntities;
			}
			set
			{
				this._ResumeSearchEntities.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ResumeSearchResultEntities(ResumeSearchResultEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchResultSetEntity = this;
		}
		
		private void detach_ResumeSearchResultEntities(ResumeSearchResultEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchResultSetEntity = null;
		}
		
		private void attach_ResumeSearchEntities(ResumeSearchEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchResultSetEntity = this;
		}
		
		private void detach_ResumeSearchEntities(ResumeSearchEntity entity)
		{
			this.SendPropertyChanging();
			entity.ResumeSearchResultSetEntity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SavedResumeSearch")]
	internal partial class SavedResumeSearchEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Guid _criteriaSetId;
		
		private System.Guid _ownerId;
		
		private string _name;
		
		private System.DateTime _createdTime;
		
		private EntityRef<ResumeSearchCriteriaSetEntity> _ResumeSearchCriteriaSetEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OncriteriaSetIdChanging(System.Guid value);
    partial void OncriteriaSetIdChanged();
    partial void OnownerIdChanging(System.Guid value);
    partial void OnownerIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncreatedTimeChanging(System.DateTime value);
    partial void OncreatedTimeChanged();
    #endregion
		
		public SavedResumeSearchEntity()
		{
			this._ResumeSearchCriteriaSetEntity = default(EntityRef<ResumeSearchCriteriaSetEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_criteriaSetId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid criteriaSetId
		{
			get
			{
				return this._criteriaSetId;
			}
			set
			{
				if ((this._criteriaSetId != value))
				{
					if (this._ResumeSearchCriteriaSetEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncriteriaSetIdChanging(value);
					this.SendPropertyChanging();
					this._criteriaSetId = value;
					this.SendPropertyChanged("criteriaSetId");
					this.OncriteriaSetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid ownerId
		{
			get
			{
				return this._ownerId;
			}
			set
			{
				if ((this._ownerId != value))
				{
					this.OnownerIdChanging(value);
					this.SendPropertyChanging();
					this._ownerId = value;
					this.SendPropertyChanged("ownerId");
					this.OnownerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime createdTime
		{
			get
			{
				return this._createdTime;
			}
			set
			{
				if ((this._createdTime != value))
				{
					this.OncreatedTimeChanging(value);
					this.SendPropertyChanging();
					this._createdTime = value;
					this.SendPropertyChanged("createdTime");
					this.OncreatedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchCriteriaSetEntity_SavedResumeSearchEntity", Storage="_ResumeSearchCriteriaSetEntity", ThisKey="criteriaSetId", OtherKey="id", IsForeignKey=true)]
		public ResumeSearchCriteriaSetEntity ResumeSearchCriteriaSetEntity
		{
			get
			{
				return this._ResumeSearchCriteriaSetEntity.Entity;
			}
			set
			{
				ResumeSearchCriteriaSetEntity previousValue = this._ResumeSearchCriteriaSetEntity.Entity;
				if (((previousValue != value) 
							|| (this._ResumeSearchCriteriaSetEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResumeSearchCriteriaSetEntity.Entity = null;
						previousValue.SavedResumeSearchEntities.Remove(this);
					}
					this._ResumeSearchCriteriaSetEntity.Entity = value;
					if ((value != null))
					{
						value.SavedResumeSearchEntities.Add(this);
						this._criteriaSetId = value.id;
					}
					else
					{
						this._criteriaSetId = default(System.Guid);
					}
					this.SendPropertyChanged("ResumeSearchCriteriaSetEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResumeSearch")]
	internal partial class ResumeSearchEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.DateTime _startTime;
		
		private System.Nullable<long> _duration;
		
		private string _context;
		
		private System.Guid _criteriaSetId;
		
		private System.Guid _resultSetId;
		
		private System.Nullable<System.Guid> _searcherId;
		
		private string _searcherIp;
		
		private System.Nullable<System.Guid> _savedSearchId;
		
		private EntityRef<ResumeSearchCriteriaSetEntity> _ResumeSearchCriteriaSetEntity;
		
		private EntityRef<ResumeSearchResultSetEntity> _ResumeSearchResultSetEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnstartTimeChanging(System.DateTime value);
    partial void OnstartTimeChanged();
    partial void OndurationChanging(System.Nullable<long> value);
    partial void OndurationChanged();
    partial void OncontextChanging(string value);
    partial void OncontextChanged();
    partial void OncriteriaSetIdChanging(System.Guid value);
    partial void OncriteriaSetIdChanged();
    partial void OnresultSetIdChanging(System.Guid value);
    partial void OnresultSetIdChanged();
    partial void OnsearcherIdChanging(System.Nullable<System.Guid> value);
    partial void OnsearcherIdChanged();
    partial void OnsearcherIpChanging(string value);
    partial void OnsearcherIpChanged();
    partial void OnsavedSearchIdChanging(System.Nullable<System.Guid> value);
    partial void OnsavedSearchIdChanged();
    #endregion
		
		public ResumeSearchEntity()
		{
			this._ResumeSearchCriteriaSetEntity = default(EntityRef<ResumeSearchCriteriaSetEntity>);
			this._ResumeSearchResultSetEntity = default(EntityRef<ResumeSearchResultSetEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				if ((this._startTime != value))
				{
					this.OnstartTimeChanging(value);
					this.SendPropertyChanging();
					this._startTime = value;
					this.SendPropertyChanged("startTime");
					this.OnstartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="BigInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<long> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this.OndurationChanging(value);
					this.SendPropertyChanging();
					this._duration = value;
					this.SendPropertyChanged("duration");
					this.OndurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_context", DbType="VarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string context
		{
			get
			{
				return this._context;
			}
			set
			{
				if ((this._context != value))
				{
					this.OncontextChanging(value);
					this.SendPropertyChanging();
					this._context = value;
					this.SendPropertyChanged("context");
					this.OncontextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_criteriaSetId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid criteriaSetId
		{
			get
			{
				return this._criteriaSetId;
			}
			set
			{
				if ((this._criteriaSetId != value))
				{
					if (this._ResumeSearchCriteriaSetEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncriteriaSetIdChanging(value);
					this.SendPropertyChanging();
					this._criteriaSetId = value;
					this.SendPropertyChanged("criteriaSetId");
					this.OncriteriaSetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultSetId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid resultSetId
		{
			get
			{
				return this._resultSetId;
			}
			set
			{
				if ((this._resultSetId != value))
				{
					if (this._ResumeSearchResultSetEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnresultSetIdChanging(value);
					this.SendPropertyChanging();
					this._resultSetId = value;
					this.SendPropertyChanged("resultSetId");
					this.OnresultSetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searcherId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> searcherId
		{
			get
			{
				return this._searcherId;
			}
			set
			{
				if ((this._searcherId != value))
				{
					this.OnsearcherIdChanging(value);
					this.SendPropertyChanging();
					this._searcherId = value;
					this.SendPropertyChanged("searcherId");
					this.OnsearcherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searcherIp", DbType="VarChar(39)", UpdateCheck=UpdateCheck.Never)]
		public string searcherIp
		{
			get
			{
				return this._searcherIp;
			}
			set
			{
				if ((this._searcherIp != value))
				{
					this.OnsearcherIpChanging(value);
					this.SendPropertyChanging();
					this._searcherIp = value;
					this.SendPropertyChanged("searcherIp");
					this.OnsearcherIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_savedSearchId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> savedSearchId
		{
			get
			{
				return this._savedSearchId;
			}
			set
			{
				if ((this._savedSearchId != value))
				{
					this.OnsavedSearchIdChanging(value);
					this.SendPropertyChanging();
					this._savedSearchId = value;
					this.SendPropertyChanged("savedSearchId");
					this.OnsavedSearchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchCriteriaSetEntity_ResumeSearchEntity", Storage="_ResumeSearchCriteriaSetEntity", ThisKey="criteriaSetId", OtherKey="id", IsForeignKey=true)]
		public ResumeSearchCriteriaSetEntity ResumeSearchCriteriaSetEntity
		{
			get
			{
				return this._ResumeSearchCriteriaSetEntity.Entity;
			}
			set
			{
				ResumeSearchCriteriaSetEntity previousValue = this._ResumeSearchCriteriaSetEntity.Entity;
				if (((previousValue != value) 
							|| (this._ResumeSearchCriteriaSetEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResumeSearchCriteriaSetEntity.Entity = null;
						previousValue.ResumeSearchEntities.Remove(this);
					}
					this._ResumeSearchCriteriaSetEntity.Entity = value;
					if ((value != null))
					{
						value.ResumeSearchEntities.Add(this);
						this._criteriaSetId = value.id;
					}
					else
					{
						this._criteriaSetId = default(System.Guid);
					}
					this.SendPropertyChanged("ResumeSearchCriteriaSetEntity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ResumeSearchResultSetEntity_ResumeSearchEntity", Storage="_ResumeSearchResultSetEntity", ThisKey="resultSetId", OtherKey="id", IsForeignKey=true)]
		public ResumeSearchResultSetEntity ResumeSearchResultSetEntity
		{
			get
			{
				return this._ResumeSearchResultSetEntity.Entity;
			}
			set
			{
				ResumeSearchResultSetEntity previousValue = this._ResumeSearchResultSetEntity.Entity;
				if (((previousValue != value) 
							|| (this._ResumeSearchResultSetEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ResumeSearchResultSetEntity.Entity = null;
						previousValue.ResumeSearchEntities.Remove(this);
					}
					this._ResumeSearchResultSetEntity.Entity = value;
					if ((value != null))
					{
						value.ResumeSearchEntities.Add(this);
						this._resultSetId = value.id;
					}
					else
					{
						this._resultSetId = default(System.Guid);
					}
					this.SendPropertyChanged("ResumeSearchResultSetEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
