#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkMe.Query.Reports.Roles.Networking.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LinkMe")]
	public partial class NetworkingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNetworkInvitationEntity(NetworkInvitationEntity instance);
    partial void UpdateNetworkInvitationEntity(NetworkInvitationEntity instance);
    partial void DeleteNetworkInvitationEntity(NetworkInvitationEntity instance);
    partial void InsertUserToUserRequestEntity(UserToUserRequestEntity instance);
    partial void UpdateUserToUserRequestEntity(UserToUserRequestEntity instance);
    partial void DeleteUserToUserRequestEntity(UserToUserRequestEntity instance);
    #endregion
		
		public NetworkingDataContext() : 
				base(global::LinkMe.Query.Reports.Properties.Settings.Default.LinkMeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NetworkingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NetworkingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NetworkingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NetworkingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		internal System.Data.Linq.Table<NetworkInvitationEntity> NetworkInvitationEntities
		{
			get
			{
				return this.GetTable<NetworkInvitationEntity>();
			}
		}
		
		internal System.Data.Linq.Table<UserToUserRequestEntity> UserToUserRequestEntities
		{
			get
			{
				return this.GetTable<UserToUserRequestEntity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NetworkInvitation")]
	internal partial class NetworkInvitationEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _inviteeEmailAddress;
		
		private System.Guid _inviterId;
		
		private System.Nullable<System.Guid> _inviteeId;
		
		private System.Nullable<System.Guid> _donationRequestId;
		
		private EntityRef<UserToUserRequestEntity> _UserToUserRequestEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OninviteeEmailAddressChanging(string value);
    partial void OninviteeEmailAddressChanged();
    partial void OninviterIdChanging(System.Guid value);
    partial void OninviterIdChanged();
    partial void OninviteeIdChanging(System.Nullable<System.Guid> value);
    partial void OninviteeIdChanged();
    partial void OndonationRequestIdChanging(System.Nullable<System.Guid> value);
    partial void OndonationRequestIdChanged();
    #endregion
		
		public NetworkInvitationEntity()
		{
			this._UserToUserRequestEntity = default(EntityRef<UserToUserRequestEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._UserToUserRequestEntity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviteeEmailAddress", DbType="NVarChar(320)", UpdateCheck=UpdateCheck.Never)]
		public string inviteeEmailAddress
		{
			get
			{
				return this._inviteeEmailAddress;
			}
			set
			{
				if ((this._inviteeEmailAddress != value))
				{
					this.OninviteeEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._inviteeEmailAddress = value;
					this.SendPropertyChanged("inviteeEmailAddress");
					this.OninviteeEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviterId", DbType="UniqueIdentifier NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.Guid inviterId
		{
			get
			{
				return this._inviterId;
			}
			set
			{
				if ((this._inviterId != value))
				{
					this.OninviterIdChanging(value);
					this.SendPropertyChanging();
					this._inviterId = value;
					this.SendPropertyChanged("inviterId");
					this.OninviterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviteeId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> inviteeId
		{
			get
			{
				return this._inviteeId;
			}
			set
			{
				if ((this._inviteeId != value))
				{
					this.OninviteeIdChanging(value);
					this.SendPropertyChanging();
					this._inviteeId = value;
					this.SendPropertyChanged("inviteeId");
					this.OninviteeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donationRequestId", DbType="UniqueIdentifier", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.Guid> donationRequestId
		{
			get
			{
				return this._donationRequestId;
			}
			set
			{
				if ((this._donationRequestId != value))
				{
					this.OndonationRequestIdChanging(value);
					this.SendPropertyChanging();
					this._donationRequestId = value;
					this.SendPropertyChanged("donationRequestId");
					this.OndonationRequestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserToUserRequestEntity_NetworkInvitationEntity", Storage="_UserToUserRequestEntity", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public UserToUserRequestEntity UserToUserRequestEntity
		{
			get
			{
				return this._UserToUserRequestEntity.Entity;
			}
			set
			{
				UserToUserRequestEntity previousValue = this._UserToUserRequestEntity.Entity;
				if (((previousValue != value) 
							|| (this._UserToUserRequestEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UserToUserRequestEntity.Entity = null;
						previousValue.NetworkInvitationEntity = null;
					}
					this._UserToUserRequestEntity.Entity = value;
					if ((value != null))
					{
						value.NetworkInvitationEntity = this;
						this._id = value.id;
					}
					else
					{
						this._id = default(System.Guid);
					}
					this.SendPropertyChanged("UserToUserRequestEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserToUserRequest")]
	internal partial class UserToUserRequestEntity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private System.Nullable<System.DateTime> _actionedTime;
		
		private System.Nullable<System.DateTime> _firstSentTime;
		
		private byte _flags;
		
		private System.Nullable<System.DateTime> _lastSentTime;
		
		private string _messageText;
		
		private byte _status;
		
		private EntityRef<NetworkInvitationEntity> _NetworkInvitationEntity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnactionedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnactionedTimeChanged();
    partial void OnfirstSentTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnfirstSentTimeChanged();
    partial void OnflagsChanging(byte value);
    partial void OnflagsChanged();
    partial void OnlastSentTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastSentTimeChanged();
    partial void OnmessageTextChanging(string value);
    partial void OnmessageTextChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public UserToUserRequestEntity()
		{
			this._NetworkInvitationEntity = default(EntityRef<NetworkInvitationEntity>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionedTime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> actionedTime
		{
			get
			{
				return this._actionedTime;
			}
			set
			{
				if ((this._actionedTime != value))
				{
					this.OnactionedTimeChanging(value);
					this.SendPropertyChanging();
					this._actionedTime = value;
					this.SendPropertyChanged("actionedTime");
					this.OnactionedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstSentTime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> firstSentTime
		{
			get
			{
				return this._firstSentTime;
			}
			set
			{
				if ((this._firstSentTime != value))
				{
					this.OnfirstSentTimeChanging(value);
					this.SendPropertyChanging();
					this._firstSentTime = value;
					this.SendPropertyChanged("firstSentTime");
					this.OnfirstSentTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flags", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte flags
		{
			get
			{
				return this._flags;
			}
			set
			{
				if ((this._flags != value))
				{
					this.OnflagsChanging(value);
					this.SendPropertyChanging();
					this._flags = value;
					this.SendPropertyChanged("flags");
					this.OnflagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastSentTime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> lastSentTime
		{
			get
			{
				return this._lastSentTime;
			}
			set
			{
				if ((this._lastSentTime != value))
				{
					this.OnlastSentTimeChanging(value);
					this.SendPropertyChanging();
					this._lastSentTime = value;
					this.SendPropertyChanged("lastSentTime");
					this.OnlastSentTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_messageText", DbType="NVarChar(2000)", UpdateCheck=UpdateCheck.Never)]
		public string messageText
		{
			get
			{
				return this._messageText;
			}
			set
			{
				if ((this._messageText != value))
				{
					this.OnmessageTextChanging(value);
					this.SendPropertyChanging();
					this._messageText = value;
					this.SendPropertyChanged("messageText");
					this.OnmessageTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UserToUserRequestEntity_NetworkInvitationEntity", Storage="_NetworkInvitationEntity", ThisKey="id", OtherKey="id", IsUnique=true, IsForeignKey=false)]
		public NetworkInvitationEntity NetworkInvitationEntity
		{
			get
			{
				return this._NetworkInvitationEntity.Entity;
			}
			set
			{
				NetworkInvitationEntity previousValue = this._NetworkInvitationEntity.Entity;
				if (((previousValue != value) 
							|| (this._NetworkInvitationEntity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NetworkInvitationEntity.Entity = null;
						previousValue.UserToUserRequestEntity = null;
					}
					this._NetworkInvitationEntity.Entity = value;
					if ((value != null))
					{
						value.UserToUserRequestEntity = this;
					}
					this.SendPropertyChanged("NetworkInvitationEntity");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
